#let acronyms = (
  "ABB": "Asea Brown Boveri",
  "CTO": "Configured to Order",
  "DHBW":"Duale Hochschule Baden-Württemberg",
  "ETO": "Engineered to Order",
  "DC": "Direct Current",
  "AC": "Alternating Current",
  "PDS": "Power Drive Systems",
  "UL": "Underwriters Laboratories",
  "IEC": "International Electrotechnical Commission",
  "Cu-ETP": "Kupfer Electrolytic Tough Pitch",
  "EMV": "Elektromagnetische Verträglichkeit",
  "CFD": "Computational Fluid Dynamics",
  "SiC": "Siliziumkarbid",
  "GaN": "Galliumnitrid",
  "SOP": "Standard Operating Procedure",
  "KPI": "Key Performance Indicator",
)