#import "../lib/lib.typ": *

= Einleitung <Einleitung>
Diese Arbeit wird bei der ABB AG im Bereich System Drives (MOSD) am Standort Mannheim durchgeführt. Untersucht wird der Einsatz flexibler Kupferschienen als Alternative zu starren Schienen und Kabeln im Schaltschrankbau für Gleichstromantriebe. In diesem Absatz wird die Motivation dieser Arbeit diskutiert, die Zielsetzung erläutert und der Aufbau der Arbeit aufgezeigt.
== Motivation <Motivation>
Der Schaltschrankbau im Umfeld leistungsstarker Gleichstromantriebe befindet sich in einem Spannungsfeld aus hoher Packungsdichte, normgerechter Ausführung und wirtschaftlicher Fertigung. Mit steigender Variantenvielfalt und kundenspezifischen Anpassungen nehmen Planungs-, Montage- und Nacharbeitsaufwände deutlich zu, insbesondere wenn starre Kupferschienen komplexe dreidimensionale Geometrien, enge Biegeradien und zahlreiche Schnittstellen erfordern. Dies führt nicht nur zu erhöhten Fertigungs- und Rüstzeiten, sondern auch zu einem höheren Risiko für Toleranzkettenprobleme, Montagefehler und nachträgliche Korrekturen im Feld. Flexible Kupferschienen adressieren diese Herausforderungen, indem sie die Verlegung im engen Bauraum erleichtern, Toleranzen besser aufnehmen und die Anzahl mechanischer sowie elektrischer Schnittstellen reduzieren. Neben potenziellen Vorteilen in der Montagefreundlichkeit und Reproduzierbarkeit ergeben sich zusätzliche technische Effekte, etwa günstigere Stromverteilungs- und Erwärmungscharakteristiken, ein robusteres Verhalten bei Kurzschlusskräften sowie mögliche EMV-Vorteile durch kürzere, flächigere Stromrückführungen. Vor diesem Hintergrund stellt sich die Frage, ob und unter welchen Randbedingungen flexible Kupferschienen im spezifischen ABB-Kontext (System Drives, Mannheim) zu einer nachweislich höheren technischen Eignung und Wirtschaftlichkeit beitragen. Relevante Einflussgrößen umfassen dabei die Serienstückzahl, die Varianz der Bauformen, die Qualität und Stabilität der Lieferkette sowie normative Anforderungen und Zulassungen. Insgesamt motiviert die Kombination aus steigendem Komplexitätsdruck, Effizienzanforderungen und Qualitätssicherung die systematische Untersuchung dieser Technologieoption.

== Zielsetzung der Arbeit <Zielsetzung>
Ziel der Arbeit ist es, eine fundierte, belastbare Entscheidungsgrundlage für den Einsatz flexibler Kupferschienen im DC-Schaltschrankbau zu erarbeiten. Hierzu werden sowohl die technische Eignung als auch die wirtschaftliche Vorteilhaftigkeit und die damit verbundenen Risiken ganzheitlich bewertet. Auf technischer Ebene umfasst dies unter anderem die Bearbeitbarkeit, Kontaktierungskonzepte, Stromtragfähigkeit, thermische und mechanische Robustheit (insbesondere unter Kurzschlussbelastung), EMV-Aspekte sowie Zuverlässigkeit und Instandhaltbarkeit im Lebenszyklus. Ökonomisch werden Material- und Montagekosten, Investitionsbedarfe (Werkzeuge, Vorrichtungen, Qualifikation), Durchlaufzeiten, Fehler- und Nacharbeitskosten sowie Kapitalwert- und Amortisationsbetrachtungen herangezogen. Ergänzend werden normative und regulatorische Rahmenbedingungen (einschlägige IEC-/UL-Normen), Qualitäts- und Freigabeprozesse, Lieferkettenstabilität sowie Anlaufrisiken betrachtet. Methodisch kommen ein Kriterienkatalog mit Gewichtung, eine strukturierte Risikoanalyse, ein Business-Case-Modell mit Sensitivitäts- und Szenarioanalysen sowie, wo sinnvoll, experimentelle und analytische Untersuchungen zum Einsatz. Eine Fallstudie am H4-Modul dient der praxisnahen Validierung, indem die Auswirkungen gegenüber dem aktuellen Referenzstand eines Schaltschrankes transparent gemacht werden. Ergebnis der Arbeit ist eine nachvollziehbare Empfehlung mit klar definierten Einsatzgrenzen, ein Entscheidungswerkzeug für die Variantenwahl sowie konkrete Handlungsempfehlungen für die Umsetzung.

== Aufbau der Arbeit <Aufbau>
Ausgehend von den Grundlagen werden die für den Schaltschrankbau relevanten technischen Prinzipien, die Charakteristika starrer und flexibler Kupferschienen sowie die maßgeblichen Normen und Zulassungsanforderungen zusammengefasst. Im Anschluss werden Stand der Technik und Forschung dargestellt, industrielle Lösungen und verfügbare Produkte eingeordnet und offene Fragestellungen herausgearbeitet. Die Methodik umfasst den Aufbau eines Kriterienkatalogs, das Bewertungs- und Entscheidungsverfahren, die Ausgestaltung des Business Case mit Datenerhebung, Annahmenmanagement und Validierung sowie die Vorgehensweise zur Risiko- und Technikbewertung. Die wirtschaftliche Analyse nutzt Kostenmodelle, Sensitivitätsrechnungen und Szenarien, leitet Schwellenwerte und Skalenwirkungen ab und formuliert eine erste ökonomische Empfehlung. Eine H4-Fallstudie überführt die Erkenntnisse in die Anwendung, vergleicht flexible Kupferschienen mit dem aktuellen Referenzschaltschrank und bewertet empirisch die Effekte auf Bauraum, Montage, Kosten und Performance. Die technische Analyse vertieft die Eignung durch analytische Abschätzungen und, wo verfügbar, experimentelle Prüfungen zu Stromtragfähigkeit, Erwärmung, Kurzschlussverhalten und elektromagnetischer Verträglichkeit. Die Diskussion ordnet die Ergebnisse kritisch ein, benennt Unsicherheiten und Grenzen der Übertragbarkeit, zeigt Optimierungspotenziale auf und verortet die Resultate im industriellen Kontext. Das Fazit beantwortet die Forschungsfrage, verdichtet die Erkenntnisse zu einer Entscheidungs- und Umsetzungshilfe und skizziert weitere Arbeiten sowie mögliche Wege der Skalierung und Industrialisierung.