#import "../lib/lib.typ": *

= Einleitung <Einleitung>

== Motivation <Motivation>
Der Schaltschrankbau im Umfeld leistungsstarker Gleichstromantriebe befindet sich in einem Spannungsfeld aus hoher Packungsdichte, normgerechter Ausführung und wirtschaftlicher Fertigung. Mit steigender Variantenvielfalt und kundenspezifischen Anpassungen nehmen Planungs-, Montage- und Nacharbeitsaufwände deutlich zu, insbesondere wenn starre Kupferschienen komplexe dreidimensionale Geometrien, enge Biegeradien und zahlreiche Schnittstellen erfordern. Dies führt nicht nur zu erhöhten Fertigungs- und Rüstzeiten, sondern auch zu einem höheren Risiko für Toleranzkettenprobleme, Montagefehler und nachträgliche Korrekturen im Feld. Flexible Kupferschienen adressieren diese Herausforderungen, indem sie die Verlegung im engen Bauraum erleichtern, Toleranzen besser aufnehmen und die Anzahl mechanischer sowie elektrischer Schnittstellen reduzieren. Neben potenziellen Vorteilen in der Montagefreundlichkeit und Reproduzierbarkeit ergeben sich zusätzliche technische Effekte, etwa günstigere Stromverteilungs- und Erwärmungscharakteristiken, ein robusteres Verhalten bei Kurzschlusskräften sowie mögliche EMV-Vorteile durch kürzere, flächigere Stromrückführungen. Vor diesem Hintergrund stellt sich die Frage, ob und unter welchen Randbedingungen flexible Kupferschienen im spezifischen ABB-Kontext (System Drives, Mannheim) zu einer nachweislich höheren technischen Eignung und Wirtschaftlichkeit beitragen. Relevante Einflussgrößen umfassen dabei die Serienstückzahl, die Varianz der Bauformen, die Qualität und Stabilität der Lieferkette sowie normative Anforderungen und Zulassungen. Insgesamt motiviert die Kombination aus steigendem Komplexitätsdruck, Effizienzanforderungen und Qualitätssicherung die systematische Untersuchung dieser Technologieoption.

== Zielsetzung der Arbeit <Zielsetzung>
Ziel der Arbeit ist es, eine fundierte, belastbare Entscheidungsgrundlage für den Einsatz flexibler Kupferschienen im DC-Schaltschrankbau zu erarbeiten. Hierzu werden sowohl die technische Eignung als auch die wirtschaftliche Vorteilhaftigkeit und die damit verbundenen Risiken ganzheitlich bewertet. Auf technischer Ebene umfasst dies u. a. die Bearbeitbarkeit, Kontaktierungskonzepte, Stromtragfähigkeit, thermische und mechanische Robustheit (insbesondere unter Kurzschlussbelastung), EMV-Aspekte sowie Zuverlässigkeit und Instandhaltbarkeit im Lebenszyklus. Ökonomisch werden Material- und Montagekosten, Investitionsbedarfe (Werkzeuge, Vorrichtungen, Qualifikation), Durchlaufzeiten, Fehler- und Nacharbeitskosten sowie Kapitalwert- und Amortisationsbetrachtungen herangezogen. Ergänzend werden normative und regulatorische Rahmenbedingungen (z. B. einschlägige IEC-/UL-Normen), Qualitäts- und Freigabeprozesse, Lieferkettenstabilität sowie Anlaufrisiken betrachtet. Methodisch kommen ein Kriterienkatalog mit Gewichtung, eine strukturierte Risikoanalyse, ein Business-Case-Modell mit Sensitivitäts- und Szenarioanalysen sowie, wo sinnvoll, experimentelle und analytische Untersuchungen zum Einsatz. Eine Fallstudie am H4‑Modul dient der praxisnahen Validierung, indem die Auswirkungen gegenüber dem aktuellen Referenzstand eines Schaltschrankes transparent gemacht werden. Ergebnis der Arbeit ist eine nachvollziehbare Empfehlung mit klar definierten Einsatzgrenzen, ein Entscheidungswerkzeug für die Variantenwahl sowie konkrete Handlungsempfehlungen für die Umsetzung.

== Aufbau der Arbeit <Aufbau>
Ausgehend von @Grundlagen werden zunächst die für den Schaltschrankbau relevanten technischen Grundlagen, die Charakteristika starrer und flexibler Kupferschienen sowie die maßgeblichen Normen und Zulassungsanforderungen zusammengefasst. Daran anschließend stellt Kapitel 3 den Stand von Technik und Forschung dar, ordnet industrielle Lösungen und verfügbare Produkte ein und identifiziert offene Fragestellungen. Kapitel 4 beschreibt die Methodik: den Aufbau des Kriterienkatalogs, das Bewertungs- und Entscheidungsverfahren, die Ausgestaltung des Business Case einschließlich Datenerhebung, Annahmenmanagement und Validierung sowie die Vorgehensweise zur Risiko- und Technikbewertung. Kapitel 5 präsentiert die wirtschaftliche Analyse mit Kostenmodellen, Sensitivitätsrechnungen und Szenarien, leitet Schwellenwerte und Skalenwirkungen ab und formuliert eine erste ökonomische Empfehlung. Kapitel 6 überträgt die Erkenntnisse in eine H4‑Fallstudie, in der flexible Kupferschienen gegen den aktuellen Schaltschrankreferenzstand verglichen und die Effekte auf Bauraum, Montage, Kosten und Performance empirisch bewertet werden. Kapitel 7 vertieft die technische Eignung durch analytische Abschätzungen und, wo verfügbar, experimentelle Prüfungen zu Stromtragfähigkeit, Erwärmung, Kurzschlussverhalten und EMV. Kapitel 8 diskutiert die Ergebnisse kritisch, beleuchtet Unsicherheiten und Grenzen der Übertragbarkeit, zeigt Optimierungspotenziale auf und verortet die Resultate im industriellen Kontext. Kapitel 9 beantwortet schließlich die Forschungsfrage, verdichtet die Erkenntnisse zu einer Entscheidungs- und Umsetzungshilfe und gibt einen Ausblick auf weitere Arbeiten und mögliche Skalierungs- bzw. Industrialisierungspfade.