#import "../lib/lib.typ": *
#pagebreak()
= Grundlagen <Grundlagen> 
Dieses Kapitel bündelt die Grundlagen für den DC-Schaltschrankbau. Es beschreibt die Systemarchitektur mit zentralen Baugruppen und Schnittstellen, erläutert Aufgaben und Dimensionierungsprinzipien von Kupferschienen und skizziert materialbezogene Kenngrößen wie Stromtragfähigkeit und zulässige Erwärmung. Ein kurzer Vergleich zwischen starren und flexiblen Ausführungen zeigt typische Einsatzbereiche und Grenzen. Abschließend werden die relevanten Normen und Randbedingungen umrissen, die den späteren Analysen und der Fallstudie zugrunde liegen.

== Einführung in den Schaltschrankbau <EinführungSchaltschrankbau>

 Die Schaltschranksysteme zeichnen sich durch ein flexibles und platzsparendes Design aus, das eine hohe Systemintegration ermöglicht. Ein wesentlicher Aspekt der Systemauslegung ist die Gewährleistung von Sicherheit und Betriebszuverlässigkeit durch den Einsatz robuster Materialien, umfassenden Berührungsschutz, Schutzisolierungen und eine strukturierte Trennung von Leistungs- und Steuerstromkreisen. Ein Schaltschrank besteht aus mehreren systematisch integrierten Komponenten, die in der standorteigenen Fertigung zu einer funktionalen Einheit zusammengefügt werden. Diese Komponenten sind je nach Kunden und Auftrag sehr unterschiedlich da #acrs("ABB") ein breites Spektrum an vorkonfigurierten sowie an Einzelanfertigungen anbietet. Hierbei kann es sich um ein Einzelschrank (Single Drive) oder aber auch um einen Gruppenantrieb (Multidrive) handeln. Der Aufbau eines solchen Schaltschrankes wird anhand @SchaltschrankAufbau von links nach rechts erklärt.

#figure( 
        image("Schaltschrank.png", height: 50%,  fit: "stretch"),
        caption: [Aufbau eines DC-Schaltschranks: @weylandEigeneDarstellunga],
    )<SchaltschrankAufbau>

Das tragende Grundgerüst ist eine Konstruktion aus C-Profilen mit einem 25 mm Raster, damit diese C-Profile nicht durch die im Betrieb entstehenden induktive Effekte überhitzen, werden bei bestimmten Ausgangsströmen zum Teil Edelstahlprofile eingesetzt, um dies zu verhindern. Die Profilgrundkonstruktion wird mit Bodenblechen versehen, auf denen später das Modul und weitere Komponenten montiert werden. Zusätzliche C-Profile dienen als Trägerstruktur für die Montageplatte und die Eingangsstromschienen. Dieser mechanische Grundaufbau ist die Basis der DC-Schaltanlagen.


Im linken Teil des Schaltschrankes ist das #acrs("AC")-Incoming Feld, darin befinden sich die Kupferschienen für die Kundenanschlüsse für die Wechselstromversorgung des Systems. Die Kupferschienen sind in der Regel massive, rechteckige oder flachkantige Profile, deren Querschnitt entsprechend der maximal zu erwartenden Stromstärke ausgelegt wird. Je nach verwendeter Norm werden die Oberflächen verzinnt, um normgerecht zu sein. Hier werden Kupferschienen mechanisch an speziellen Halterungen montiert, diese Befestigungen erfüllen des Weiteren den Zweck bei einem Kurzschluss dass sich die Schienen nicht zu sehr verziehen können. Die Kupferschienen sind dazu da um eine elektrische Verbindung zwischen den Kundenanschlüssen und dem Modul herzustellen. Der Kunde kann hier mit Kupferkabeln an die drei Phasen L1, L2 und L3 anschließen. Für eine sichere Installation sind die Schienen mit Berührungsschutz aus Gitterblech versehen, die das Risiko von Stromunfällen reduzieren.

Neben dem Incoming Feld ist das #acrs("DC")-Outcoming Feld, welches die Kupferschienen für den Gleichstrom des Systems zuständig ist. Diese Kupferschienen sind ebenfalls mechanisch an speziellen Halterungen montiert und erfüllen die gleichen Sicherheitsanforderungen wie die #acrs("AC")-Kupferschienen. Hier kann der Kunde ebenfalls Kupferkabel anschließen, um den #acrs("DC")-Strom an seine Verbraucher wie Motoren, Elektrolysatoren oder Heizspiralen weiterzuleiten. Vor den #acrs("DC")-Stromschienen befinden sich noch einige Sicherungen und Schütze, die den #acrs("DC")-Stromkreis absichern und schützen.

Das Modulfeld welches sich neben dem #acrs("DC")-Feld im Schaltschrank befindet ist mit den Kupferschienen aus dem #acrs("AC") und #acrs("DC")-Feld verbunden. Je nach Ausführung des Moduls können Ausgangsströme von 20 A bis 5200 A erreicht werden, bei #acrs("ABB") gibt es acht verschiedene Ausführungen (@DCS880[Abb.]). 
#figure( 
        image("DCS880.png", width: 100%,  fit: "stretch"),
        caption: [DCS880 Produktfamilie @DCS880Catalog[S.13]],
    )<DCS880>

#pagebreak()

Das Modul ist ein Thyristor-Gleichrichter in unterschiedlichen Ausführungen, die je nach Anwendungsfall und Kundenanforderungen ausgewählt werden. Die Thyristorschaltung ist eine 6-Puls-Brückenschaltung für einen Vorwärtslauf mit Bremsfunktion, die aus einem dreiphasigen Eingangsstrom einen Gleichstrom erzeugt (@B6U)@DrehstromGleichrichtschaltungen.
#figure( 
        image("/B6U.PNG", width: 60%,  fit: "stretch"),
        caption: [6-Puls-Brückenschaltung @FragenGleichrichterschaltungFuer2016],
    )<B6U>
 Dieser Gleichstrom wird durch Kondensatoren geglättet, um eine gleichmäßige Stromkurve zu gewährleisten. Die Thyristoren können mit verschiedenen Zündwinkeln gezündet werden, um unterschiedliche Ausgangsströme zu erreichen. Ein Thyristor ist ein Halbleiterbauelement, das als Schalter fungiert und in der Lage ist, hohe Spannungen und Ströme zu steuern. Die Zündung erfolgt über eine Steuerleitung, die auf die im Thyristor befindliche Halbleiterschicht wirkt und den Strom so verteilt, dass das Bauelement leitend wird. Sobald der Thyristor gezündet ist, bleibt er leitend, bis der Strom unter einen bestimmten Wert fällt oder die Zündung zurückgesetzt wird. Diese Technologie ermöglicht eine präzise Steuerung des Gleichstroms und ist besonders effizient für Anwendungen mit hohen Leistungsanforderungen.

Im ganz rechten Feld des Schaltschrankes befindet sich die Montageplatte (@Montageplatte[Abb.]). Die Montageplatte stellt als zentrale Trägerstruktur eine lasergefertigte Metallplatte dar, die typischerweise aus Stahl besteht. Auf dieser werden elektrische Bauteile wie Schütze, Relais, Sicherungen und Steuereinrichtungen montiert. Die konstruktive Auslegung der Montageplatte gewährleistet sowohl eine stabile mechanische Basis für die Montage der elektrischen Komponenten als auch eine optimierte Wärmeableitung zur Vermeidung thermischer Überlastungen. Die Befestigung erfolgt mittels Schrauben oder Bolzen am Schaltschrankgestell, wobei eine modulare Erweiterbarkeit berücksichtigt wird.
#figure( 
        image("/chapters/Bachelor/Montageplatte.jpeg", width: 35%,  fit: "stretch"),
        caption: [Montageplatte @weylandEigeneDarstellunga],
    )<Montageplatte>

Neben der Montageplatte ist die Steuereinheit des Moduls angeordnet. Die Steuereinheit übernimmt zentrale Aufgaben der Steuerung und Überwachung der elektrischen Komponenten und integriert dabei eine programmierbare Steuerungseinheit zur Konfiguration des Moduls, verschiedene Schnittstellen für Anzeige- und Bedienelemente sowie erweiterbare Funktionsmodule, die eine flexible Anpassung an zusätzliche Systemfunktionen erlauben. Über der Steuereinheit befindet sich der Lasttrenner des Schaltschranks sowie die Überlastschutzsicherungen. Es werden weitere Komponenten wie Transformatoren und Drosseln auf dem Bodenblech installiert, die der Stromversorgung der elektronischen Bauteile dienen.

Die abschließende Montage umfasst die Installation der Schaltschranktüren, Seitenwände sowie der Rückwände, die sowohl den Schutz vor äußeren Einflüssen wie Staub und Verschmutzung als auch die erforderliche Betriebssicherheit gewährleisten. Die Türkonstruktion aus Stahl kann entsprechend den spezifischen Anforderungen mit zusätzlichen Funktionalitäten oder Schnittstellen ausgestattet werden.

== Aufbau und Funktion von Kupferschienen <AufbauFunktionKupferschienen>

Kupferschienen (@Kupferschiene[Abb.]) sind zentrale Bauteile in Gleichstrom-Schaltschränken und dienen der effizienten und sicheren Stromverteilung. #acr("Cu-ETP") wird durch elektrolytische Raffination hergestellt und enthält einen definierten Sauerstoffgehalt. Dieses Material zeichnet sich durch eine sehr hohe elektrische und thermische Leitfähigkeit aus, die im weichen Zustand mindestens 57 m/(Ω*mm²) beträgt. @DatenblaetterKupferverband[S.2 ff.]
Halbzeuge aus #acrs("Cu-ETP") werden überwiegend aus gegossenen Vormaterialien, wie beispielsweise Walzbarren oder Gussdrähten, durch verschiedene Umformverfahren hergestellt. Das ausgeprägte Formänderungsvermögen des Werkstoffs begünstigt hierbei die Weiterverarbeitung und ermöglicht eine effiziente Fertigung komplexer Geometrien. Die eingesetzten Kupferschienen sind in der Regel massive, rechteckige oder flachkantige Profile, deren Querschnitt entsprechend der maximal zu erwartenden Stromstärke ausgelegt wird, es kann in Einzelfällen auch zu gelaserten Kupferblechen kommen, da diese sich für komplizierte Geometrien eignen. Je nach normativen Voraussetzungen werden die Oberflächen verzinnt, um Korrosion zu verhindern und die Übergangswiderstände an den Kontaktstellen gering zu halten.

#figure( 
        image("/chapters/Bachelor/Kupferschiene.jpg", width: 70%,  fit: "stretch"),
        caption: [Beispiel Kupferschiene @weylandEigeneDarstellunga],
    )<Kupferschiene>

Die Hauptfunktion der Kupferschienen besteht darin, als zentrales Verteilersystem für den Schaltschrank zu fungieren. Von ihnen aus werden verschiedene Verbraucher und Unterverteilungen verbunden, was den Anschluss zahlreicher Komponenten an  gemeinsame Sammelschienen ermöglicht. Durch den Einsatz von Kupferschienen kann im Vergleich zu Einzelkabelverbindungen erheblich Platz gespart werden, und die Verdrahtung im Schaltschrank erscheint übersichtlicher und ordentlicher. Aufgrund der guten Wärmeleitfähigkeit des Kupfers tragen die Schienen außerdem dazu bei, entstehende Wärme effektiv abzuleiten und auch hohe Ströme sicher zu führen. Darüber hinaus bieten Kupferschienen eine flexible Lösung für zukünftige Erweiterungen, da zusätzliche Abgänge ohne großen Aufwand realisiert werden können. In manchen Anwendungen unterstützen sie auch den Potentialausgleich und verbessern die #acr("EMV") im Schaltschrank. Durch den geringen spezifischen Widerstand des Kupfers werden Spannungsabfälle minimiert, was eine stabile Stromversorgung garantiert.

Die Dimensionierung der Kupferschienen erfolgt anhand der maximalen Stromstärke und der zulässigen Erwärmung, unterstützt durch Normen wie die DIN EN 61439 sowie technische Vorgaben der Hersteller. Zusätzlich ist ein wirksamer Korrosionsschutz besonders in feuchten oder industriellen Umgebungen wichtig, um die Langlebigkeit und Betriebssicherheit zu sichern. Für den nordamerikanischen Markt gelten zusätzlich die Anforderungen der UL 508A. (vgl. @IEC614390@IEC614391@IEC614392@IEC614396@UL508@deffaaDesignHandbuchDCcabinets2024[S.10])

Zusammengefasst sind Kupferschienen im DC-Schaltschrankbau unverzichtbare Komponenten, die durch ihren robusten und durchdachten Aufbau eine zuverlässige, effiziente und sichere Stromverteilung gewährleisten und somit eine wichtige Grundlage für den störungsfreien Betrieb moderner Gleichstromanlagen bilden.

== Unterschied zwischen starren und flexiblen Kupferschienen <UnterschiedStarrFlexibel>

In diesem Abschnitt werden die grundlegenden Unterschiede zwischen starren und flexiblen Kupferschienen sowie deren spezifische Vor- und Nachteile aufgezeigt.

Starre Kupferschienen (@Kupferschiene[Abb.]) bestehen aus massiven, meist durch Extrusion oder laserbearbeiteten hergestellten Kupferprofilen mit Querschnitten von bis zu 2.400 mm². Sie zeichnen sich durch eine hohe mechanische Festigkeit und Formstabilität aus, was sie insbesondere für gerade, lasttragende Verbindungen prädestiniert. Aufgrund ihres geringen elektrischen Widerstands und der großen Querschnitte eignen sie sich besonders für Anwendungen mit hohen Strombelastungen und gewährleisten eine zuverlässige elektrische Kontaktierung. Die Installation starrer Kupferschienen erfordert jedoch einen vergleichsweise hohen Planungs- und Montageaufwand, insbesondere bei komplexen Geometrien oder beengten Einbauverhältnissen. 

Flexible Kupferschienen (@FlexibleKupferschiene[Abb.]) unterscheiden sich hinsichtlich Aufbau und Materialstruktur deutlich von starren Varianten. Sie bestehen aus mehreren dünnen, übereinanderliegenden Kupferlamellen, die zur mechanischen Fixierung und elektrischen Isolierung mit einer PVC-Ummantelung versehen sind. Die Lamellen weisen typischerweise Dicken von 0,5 bis 1 mm auf; je nach Anwendungsfall können bis zu zehn Lamellen kombiniert werden, wodurch Querschnitte von bis zu 1.200 mm² realisierbar sind. @NVentERIFLEXFlexible[S.12-13] Flexible Kupferschienen bieten durch ihre Isolierung eine hohe Kurzschlussfestigkeit bis zu 120 kA und erfordern im Schaltschrankbau keine zusätzliche mechanische Abstützung im Vergleich zu starren Kupferschienen. (vgl. @deffaaDesignHandbuchDCcabinets2024)

#figure( 
        image("/chapters/Bachelor/LaminierteSchiene.png", width: 70%,  fit: "stretch"),
        caption: [Beispiel Laminierte Kupferschiene @LaminierteKupferschiene],
    )<FlexibleKupferschiene>

Eine weitere Ausführung flexibler Kupferschienen basiert auf verflochtenen Kupferlitzen, die zu einem Geflecht verarbeitet und ebenfalls mit einer PVC-Isolierung ummantelt werden. Die Enden werden in der Regel durch Pressschweißen abgeschlossen. Bei dieser Bauform sind Querschnitte bis 240 mm² möglich. @NVentERIFLEXFlexible[S.25-26] Im Vergleich zu Kabeln gleichen Querschnitts weisen diese Kupfergeflechte eine deutlich höhere Flexibilität auf und ermöglichen eine erleichterte Installation bei komplexen Einbausituationen.

Der zentrale Unterschied zwischen starren und flexiblen Kupferschienen liegt somit in deren Aufbau und den daraus resultierenden Einsatzmöglichkeiten. Während starre Kupferschienen bei großen Querschnitten nur eingeschränkt biegbar sind und daher vorwiegend für lineare Verbindungen eingesetzt werden, ermöglichen flexible Kupferschienen durch ihren Lamellen- bzw. Geflechtaufbau deutlich kleinere Biegeradien und komplexere Verlegeführungen. Dies erweitert den Einsatzbereich insbesondere in beengten oder geometrisch anspruchsvollen Anwendungen. Demgegenüber stehen höhere Material- und Herstellungskosten sowie eine Begrenzung der maximal realisierbaren Querschnitte bei flexiblen Ausführungen.

Eine detaillierte Analyse der technischen Unterschiede sowie deren Auswirkungen auf Stromtragfähigkeit, Erwärmungsverhalten und mechanische Eigenschaften erfolgt in @TechnischeAnalyse Technische Analyse.

== Normative Anforderungen <NormativeAnforderungen>

Im Schaltschrankbau spielen normative Anforderungen eine zentrale Rolle, um die Sicherheit, Funktionalität und internationale Marktfähigkeit elektrischer Anlagen zu gewährleisten. Die wichtigsten Normensysteme in diesem Bereich sind die #acr("IEC")-Normen  und die #acr("UL")-Normen, die jeweils unterschiedliche geografische und regulatorische Anforderungen abdecken.@IEC614390[Abschnitt 1]@UL508[Abschnitt 1]

Die internationale Norm IEC 61800-5-1:2022 legt die sicherheitsrelevanten Anforderungen für elektrische Antriebssysteme mit variabler Drehzahl #acr("PDS") fest. Sie beschreibt die grundlegenden Schutzmaßnahmen, die erforderlich sind, um Personen und Anlagen im Betrieb wie auch im Fehlerfall zuverlässig vor Gefahren zu schützen. Der Anwendungsbereich umfasst sowohl Niederspannungs- als auch Hochspannungsantriebssysteme, die aus Leistungsteil, Steuerung und Motor bestehen.@IEC6180051[Abschnitt 1]

Im Mittelpunkt der Norm stehen drei wesentliche Sicherheitsaspekte: elektrische, thermische und energiebezogene Gefährdungen. Auf elektrischer Ebene definiert die Norm Maßnahmen gegen den elektrischen Schlag, Anforderungen an Isolierung, Luft- und Kriechstrecken sowie Vorgaben für Schutzmechanismen bei Fehler- und Abnormalbedingungen. Im thermischen Bereich adressiert sie Risiken durch Überhitzung, Brandgefahr und die Begrenzung von zulässigen Temperaturanstiegen an Bauteilen, Leitern und berührbaren Oberflächen. Unter dem Aspekt der Energie betrachtet die Norm insbesondere Kurzschluss- und Überlastschutz, den Umgang mit gespeicherten Energien wie Kondensatoren sowie Schutzmaßnahmen gegen gefährliche Energiefreisetzungen. Darüber hinaus enthält die IEC 61800-5-1 Anforderungen an Gehäuse, Kühlung, Erdung, Verdrahtung, elektromagnetische Verträglichkeit sowie an die Kennzeichnung und Dokumentation. Damit stellt die Norm sicher, dass Antriebssysteme im Schaltschrankbau so ausgeführt werden, dass sie bei ordnungsgemäßer Installation und Wartung keine Gefahr für Personen oder Sachwerte darstellen.@IEC6180051[Abschnitt 4.4; 4.5; 4.6]

Ergänzend dazu ist die IEC 61439-Reihe von zentraler Bedeutung, da sie die Anforderungen an Niederspannungs-Schaltgerätekombinationen festlegt. Diese Normserie befasst sich insbesondere mit der Dimensionierung von Schaltschränken, einschließlich der Strombelastbarkeit von Sammelschienen, der Kurzschlussfestigkeit, der Erwärmung und der erforderlichen Prüfungen zur Sicherstellung der Betriebssicherheit. Während die IEC 61800-5-1 den Fokus auf die Sicherheit der Antriebssysteme legt, stellt die IEC 61439-Reihe sicher, dass der gesamte Schaltschrank mechanisch und elektrisch korrekt ausgelegt ist und die eingesetzten Betriebsmittel unter realen Betriebsbedingungen zuverlässig zusammenwirken. @IEC614390[Abschnitt 1]@IEC614391[Abschnitt 10; 10.10; 10.11; 10.12]@IEC614392[Abschnitt 1; 2]@IEC614396@IEC6180051[Abschnitt 3; 4.4; 4.5; 4.6]

Für den nordamerikanischen Markt ist zusätzlich die UL 508A Standard for Industrial Control Panels maßgeblich. Diese Norm definiert die sicherheitstechnischen Anforderungen an den Aufbau von industriellen Schaltschränken und Steuerungen. Sie regelt unter anderem die Auslegung von Stromschienen, Leiterquerschnitten und Schutzorganen sowie die Dimensionierung von Luft- und Kriechstrecken. Ein besonderer Schwerpunkt liegt dabei auf dem Schutz vor elektrischen Gefährdungen, der korrekten Absicherung gegen Kurzschluss und Überlast sowie auf den Anforderungen an die Erdung und den Berührungsschutz. Darüber hinaus enthält die UL 508A praxisnahe Vorgaben für den Aufbau, die Verdrahtung, die Dokumentation und die Kennzeichnung von Schaltschränken. Sie bildet damit die Grundlage für eine normgerechte und sichere Ausführung von Steuerungs- und Antriebssystemen für den nordamerikanischen Markt.@UL508[Abschnitt 1; 10; 14-17; 28] @UL6180051[S.268ff.; S.328 ff.; Anhang S]

#acrs("ABB") stellt ein unternehmensinternes Dokument bereit, das die wichtigsten oben genannten normativen Anforderungen aus den relevanten Normen systematisch zusammenfasst und dem Engineering-Team als umfassender Designleitfaden dient. Darüber hinaus wurden unternehmensspezifische Grenzwerte für die Dimensionierung von Kupferschienen definiert, um den Kunden ein noch höheres Maß an Sicherheit und Zuverlässigkeit zu gewährleisten. Eine zentrale Normenbibliothek unterstützt die konsequente Einhaltung dieser Standards und fördert die Entwicklung sicherer sowie effizienter Lösungen.@deffaaDesignHandbuchDCcabinets2024
