#import "../lib/lib.typ": *

= Grundlagen <Grundlagen> 
Die vorliegende Arbeit wird in der ABB AG am Standort Mannheim, innerhalb der Business Unit Motion in der Abteilung System Drives geschrieben. Die Abteilung ist spezialisiert auf die Entwicklung, Konstruktion und Fertigung von konfigurierten sowie kundenspezifisch ausgelegten Schaltschränken, in denen ausschließlich ABB-Module wie der DCS880 und DCT880 integriert werden. Bei diesen Modulen handelt es sich um leistungsfähige Gleichrichter, die mittels Thyristortechnologie Gleichstrom erzeugen. Die gefertigten Schaltschränke sind für die zuverlässige Energieverteilung und die präzise Steuerung von Motoren und industriellen Anlagen konzipiert und erfüllen hohe Anforderungen hinsichtlich Funktionalität, Sicherheit und Systemintegration.

== Einführung in den Schaltschrankbau <EinführungSchaltschrankbau>

Ein Schaltschrank besteht aus mehreren systematisch integrierten Komponenten, die in der industriellen Fertigung zu einer funktionalen Einheit zusammengefügt werden. Das tragende Grundgerüst bildet eine Konstruktion aus C-Profilen, die je nach den zu erwartenden Betriebsströmen aus Stahl oder Edelstahl gefertigt werden, damit diese C-Profile nicht durch die Induktion überhitzen. Diese Profilkonstruktion nimmt Bodenbleche und zusätzliche C-Profile auf, welche als Trägerstruktur für die Montageplatte mit den elektrischen Komponenten fungieren.

Die Montageplatte stellt als zentrale Trägerstruktur eine präzisionsgefertigte Metallplatte dar, die typischerweise aus Stahl besteht. Auf dieser werden elektrische Bauteile wie Schütze, Relais, Sicherungen und Steuereinrichtungen montiert. Die konstruktive Auslegung der Montageplatte gewährleistet sowohl eine stabile mechanische Basis für die Montage der elektrischen Komponenten als auch eine optimierte Wärmeableitung zur Vermeidung thermischer Überlastungen. Die Befestigung erfolgt mittels Schrauben oder Bolzen am Schaltschrankgestell, wobei eine modulare Erweiterbarkeit berücksichtigt wird.

Vor der Montageplatte wird die Steuereinheit des Moduls positioniert, deren Zugänglichkeit durch einen Schwenkrahmen realisiert wird. Dieser ermöglicht das Vorklappen der Steuereinheit für Wartungs- und Instandhaltungsarbeiten an der dahinterliegenden Montageplatte. Die Steuereinheit übernimmt dabei zentrale Funktionen der Steuerung und Überwachung der elektrischen Komponenten und beinhaltet:

- Eine programmierbare Steuerungseinheit für die Konfiguration des Moduls
- Schnittstellen für Anzeige- und Bedienelemente
- Erweiterbare Funktionsmodule für zusätzliche Systemfunktionen

In den hinteren Teil des Schaltschrankes kommen nun die Sammelschienen und Stromschienen die dann zum Modul führen. Diese Kupferschienen verbinden den Kundenanschluss mit dem Modul und stellen die elektrische Verbindung zwischen den verschiedenen Komponenten des Schaltschranks her. Ebenso dienen diese Kupferschienen als abgangs Schienen für die Verbindung zu den elektrischen Verbrauchern wie Motoren, Elektrolysatoren oder heißSpiralen. Die Kupferschienen sind in der Regel massive, rechteckige oder flachkantige Profile, deren Querschnitt entsprechend der maximal zu erwartenden Stromstärke ausgelegt wird. Je nach verwendeter Norm werden die Oberflächen verzinnt oder anderweitig veredelt, um Normgerecht zu sein. Für eine sichere Installation sind die Schienen mit Isolatoren und Berührungsschutz versehen, beispielsweise durch Acrylglasabdeckungen, die das Risiko von Kurzschlüssen oder Stromunfällen reduzieren. Mechanisch werden die Kupferschienen robust an speziellen Halterungen oder Tragschienen befestigt, sodass sie formstabil und vibrationsfest im Schaltschrank montiert sind. Diese Befestigungen erfüllen desweiteren den Zweck bei einem Kurzschluss das sich die Schienen nicht zu sehr verziehen können.

Das Modul wird nun in das Gestell eingesetzt und mit den Stromschienen verbunden. Je nach Ausführung des Moduls können Ausgangsströme von 20 A bis 5200 A erreicht werden. Das Modul ist ein Thyristor-Gleichrichter in unterschiedlichen Ausführungen, die je nach Anwendungsfall und Kundenanforderungen ausgewählt werden. Die Thyristorschaltung ist eine 6-Puls-Brückenschaltung, die aus einem dreiphasigen Eingangsstrom einen Gleichstrom erzeugt. Dieser Gleichstrom wird durch Kondensatoren geglättet, um eine gleichmäßige Stromkurve zu gewährleisten. Die Thyristoren können mit verschiedenen Zündwinkeln gezündet werden, um unterschiedliche Ausgangsströme zu erreichen. Ein Thyristor ist ein Halbleiterbauelement, das als Schalter fungiert und in der Lage ist, hohe Spannungen und Ströme zu steuern. Die Zündung erfolgt über eine Steuerleitung, die auf die im Thyristor befindliche Halbleiterschicht wirkt und den Strom so verteilt, dass das Bauelement leitend wird. Sobald der Thyristor gezündet ist, bleibt er leitend, bis der Strom unter einen bestimmten Wert fällt oder die Zündung zurückgesetzt wird. Diese Technologie ermöglicht eine präzise Steuerung des Gleichstroms und ist besonders effizient für Anwendungen mit hohen Leistungsanforderungen.

Nach der Integration des Moduls in das Gestell werden weitere Komponenten wie Transformatoren und Drosseln installiert, die der Stromversorgung der elektronischen Bauteile dienen. Je nach Systemkonfiguration wird ein separates Gestell für die Installation der Stromschienen errichtet. Diese Kupferschienen erfüllen die primäre Funktion der Stromverteilung im Schaltschrank und sind aufgrund ihrer hohen elektrischen Leitfähigkeit und geringen Wärmeentwicklung für eine effiziente Energieübertragung ausgelegt. Die mechanische Befestigung erfolgt über Schrauben oder Bolzen am Schaltschrankgestell, wobei eine bedarfsgerechte Anpassung und Erweiterung möglich ist.

Die abschließende Montage umfasst die Installation der Schaltschranktür, die sowohl den Schutz vor äußeren Einflüssen wie Staub und Verschmutzung als auch die erforderliche Betriebssicherheit gewährleistet. Die Türkonstruktion aus Stahl oder Edelstahl kann entsprechend den spezifischen Anforderungen mit zusätzlichen Funktionalitäten oder Schnittstellen ausgestattet werden.

In der Abteilung DC System Drives werden Schaltschränke sowohl nach konfigurierten Standardlösungen als auch nach kundenspezifischen Entwicklungen gefertigt. Der Schaltschrankbau mit ABB-Produkten der Low Voltage Division, insbesondere den Systemen DCS880 und DCT880, bildet dabei die technologische Grundlage für moderne und zuverlässige Niederspannungsverteilsysteme. ABB bietet mit diesen Baureihen skalierbare und modulare Lösungen, die speziell für die Anforderungen in der Gleichstrom- und Niederspannungsinstallation entwickelt wurden.

Die Schaltschranksysteme DCS880 und DCT880 zeichnen sich durch folgende charakteristische Eigenschaften aus:

- Flexibles, platzsparendes Design mit hoher Systemintegration
- Anwendung sowohl in der Energieverteilung als auch in der Motor- und Anlagensteuerung
- Vereinfachte und übersichtliche Verdrahtung durch intelligente Systemaufteilungen
- Standardisierte Komponenten für erleichterte Montage und spätere Systemerweiterungen
- Modulare Bauweise für vielfältige industrielle Anwendungen

Ein wesentlicher Aspekt der Systemauslegung ist die Gewährleistung von Sicherheit und Betriebszuverlässigkeit durch den Einsatz robuster Materialien, umfassenden Berührungsschutz, Schutzisolierungen und eine strukturierte Trennung von Leistungs- und Steuerstromkreisen.

ABB unterstützt die Projektierung und Fertigung durch umfangreiche digitale Planungstools wie den ABB EasyPro™ Konfigurator und EPLAN-Schnittstellen. Die Systeme DCS880 und DCT880 sind für hohe elektrische Belastbarkeit, Schutz bei Kurzschlussereignissen sowie eine nahtlose Integration in übergeordnete Automatisierungs- und Energiemanagementsysteme ausgelegt.

Durch die Verwendung normgerechter Schalttechnik und die Integration intelligenter Steuerungs- und Überwachungsfunktionen bieten diese ABB-Schaltschranksysteme eine moderne Plattform für den professionellen Niederspannungs-Schaltschrankbau und gewährleisten eine effiziente, sichere und zukunftsfähige Energieverteilung in verschiedensten industriellen und infrastrukturellen Anwendungsbereichen.

Die Produktpalette der Abteilung Low Voltage System Drives umfasst dabei insbesondere den ABB-Antrieb DCS880, der in acht verschiedenen Varianten verfügbar ist, sowie den ABB DCT880, welcher ebenfalls in acht unterschiedlichen Ausführungen angeboten wird. Diese Vielfalt ermöglicht eine bedarfsgerechte Anpassung an spezifische Anwendungsanforderungen.

== Aufbau und Funktion von Kupferschienen <AufbauFunktionKupferschienen>

Kupferschienen sind zentrale Bauteile in Gleichstrom-Schaltschränken und dienen der effizienten und sicheren Stromverteilung. Sie bestehen meist aus hochreinem Kupfer, da dieses Material eine hervorragende elektrische Leitfähigkeit besitzt und somit Verluste durch Widerstände minimiert werden. Die Kupferschienen sind in der Regel massive, rechteckige oder flachkantige Profile, deren Querschnitt entsprechend der maximal zu erwartenden Stromstärke ausgelegt wird. Oftmals werden die Oberflächen verzinnt oder anderweitig veredelt, um Korrosion zu verhindern und die Übergangswiderstände an den Kontaktstellen gering zu halten. Für eine sichere Installation sind die Schienen mit Isolatoren und Berührungsschutz versehen, beispielsweise durch Acrylglasabdeckungen, die das Risiko von Kurzschlüssen oder Stromunfällen reduzieren. Mechanisch werden die Kupferschienen robust an speziellen Halterungen oder Tragschienen befestigt, sodass sie formstabil und vibrationsfest im Schaltschrank montiert sind.

Die Hauptfunktion der Kupferschienen besteht darin, als zentrales Verteilersystem für Gleichstrom zu fungieren. Von ihnen aus werden verschiedene Verbraucher und Unterverteilungen verbunden, was den Anschluss zahlreicher Komponenten an eine gemeinsame Spannungsschiene ermöglicht. Durch den Einsatz von Kupferschienen kann im Vergleich zu Einzelkabelverbindungen erheblich Platz gespart werden, und die Verdrahtung im Schaltschrank erscheint übersichtlicher und ordentlicher. Aufgrund der guten Wärmeleitfähigkeit des Kupfers tragen die Schienen außerdem dazu bei, entstehende Wärme effektiv abzuleiten und auch hohe Ströme sicher zu führen. Die Konstruktion mit Schutzabdeckungen und Isolierungen gewährleistet eine hohe Betriebssicherheit. Darüber hinaus bieten Kupferschienen eine flexible Lösung für zukünftige Erweiterungen, da zusätzliche Abgänge ohne großen Aufwand realisiert werden können. In manchen Anwendungen unterstützen sie auch den Potentialausgleich und verbessern die elektromagnetischen Verträglichkeit (EMV) im Schaltschrank. Durch den geringen spezifischen Widerstand des Kupfers werden Spannungsabfälle minimiert, was eine stabile Stromversorgung garantiert.

Die Dimensionierung der Kupferschienen erfolgt anhand der maximalen Stromstärke und der zulässigen Erwärmung, unterstützt durch Normen wie die DIN EN 61439 sowie technische Vorgaben der Hersteller. Zusätzlich ist ein wirksamer Korrosionsschutz besonders in feuchten oder industriellen Umgebungen wichtig, um die Langlebigkeit und Betriebssicherheit zu sichern. Für den nordamerikanischen Markt gelten zusätzlich die Anforderungen der *UL 508A*, die unter anderem die Verwendung von Kupferleitungen, Mindestquerschnitte und die Auswahl UL-zertifizierter Komponenten vorschreibt [7].

Zusammengefasst sind Kupferschienen im DC-Schaltschrankbau unverzichtbare Komponenten, die durch ihren robusten und durchdachten Aufbau eine zuverlässige, effiziente und sichere Stromverteilung gewährleisten und somit eine wichtige Grundlage für den störungsfreien Betrieb moderner Gleichstromanlagen bilden.

[3](https://library.e.abb.com/public/edc51e83d85231d8c1257845002a4a8f/2CDC400027D0101.pdf): [ABB Elektrospicker zu Sammelschienensystemen (PDF)](https://library.e.abb.com/public/1089fa14184049b6ab41c01bf39f3cd3/9AKK107991A1574_Rev_B_13_Installation_Stecksockelsystem_DE_Elektrospicker_102020.pdf)
[1](https://www.mountec.de/de-de/wissensblog/aufbau_eines_schaltschranks): [ABB Produktdatenblatt ZX2782 – Kupferschiene 50×10 mm](https://new.abb.com/products/de/2CPX044283R9999/zx2782)  
[2](https://www.woehner.de/fileadmin/Downloads/03_Produkthandbuch/phb2015d_08_technische_daten.pdf): [Druseidt Belastungstabelle für Stromschienen nach DIN 43671](https://shop.druseidt.de/allgemeine-informationen/flexible-verbinder/belastungstabelle-fuer-stromschienen-aus-kupfer-nach-din-43671/)  
[3](https://sps-standard.com/isoflexx): [Kinto Power Connect – Unterschied starre/flexible Kupferschienen](https://www.kintopowerconnect.com/de/blog/What-is-the-difference-between-flexible-and-rigid-busbars)  
[4](https://www.isomet.ch/katalog/pdf/de/Kapitel_11_22-26.pdf): [ABB System pro E power – Technische Informationen](https://library.abb.com/)  
[5](https://www.eplan.help/de-DE/Infoportal/Content/Plattform/2.8/Content/htm/copper_k_arbeitsweise.htm): [Schrack Technik – Flexible Kupferschienen](https://www.schrack.at/know-how-cip/verteilereinbau-ls-fi-ueberspannungsableiter-d0-und-nh/schmelzsicherungs-und-sammelschienensysteme/flexible-kupferschienen)  
[6](https://mvg-frankfurt.de/blogs/news/die-bedeutung-von-kupfer-in-schaltschranken-vom-erzabbau-bis-zum-einsatz-von-recycling-kupfer): [DIN EN 61439 – Anforderungen an NS-Schaltgerätekombinationen](https://www.elektrofachkraft.de/sicheres-arbeiten/normenreihe-din-en-61439-niederspannungs-schaltgeraetekombination)  
[7](https://shop.druseidt.de/allgemeine-informationen/flexible-verbinder/belastungstabelle-fuer-stromschienen-aus-kupfer-nach-din-43671/): [UL 508A – Anforderungen an industrielle Steuerschränke](https://www.ul.com/sites/g/files/qbfpbp251/files/2020-04/508A%20Supplement%20SA%204_13_20_L-Rev1.pdf)

== Unterschied zwischen starren und flexiblen Kupferschienen <UnterschiedStarrFlexibel>

Der Unterschied zwischen starren und flexiblen Kupferschienen liegt im Wesentlichen in ihrer Bauweise, Anwendungsflexibilität sowie in den mechanischen Eigenschaften.

Starre Kupferschienen bestehen aus massiven, fest geformten Profilen, die in der Regel durch Extrusion oder Laserbearbeitung aus Kupfer gefertigt werden. Sie zeichnen sich durch eine hohe mechanische Stabilität aus und eignen sich insbesondere für gerade Verbindungen. Aufgrund ihres geringen elektrischen Widerstands sind sie besonders für hohe Strombelastungen prädestiniert und gewährleisten eine zuverlässige elektrische Kontaktierung.

Flexible Kupferschienen unterscheiden sich in ihrem Aufbau deutlich von den starren Varianten. Eine Bauform besteht aus mehreren dünnen Kupferlamellen, die übereinander angeordnet und zur mechanischen Fixierung mit einer Isolationsschicht ummantelt sind. Die Lamellen besitzen üblicherweise eine Stärke von 0,5 bis 1 mm je nach Anwendungsfall können bis zu zehn Lamellen kombiniert werden. Mit dieser Konstruktion lassen sich Querschnitte von bis zu 1.200 mm² realisieren, was für die meisten industriellen Einsatzbereiche ausreichend ist.

Eine weitere Ausführung flexibler Kupferschienen basiert auf verflochtenen Kupferlitzen, die zu einem großflächigen Kupfergeflecht verarbeitet werden. Zur Formstabilität und elektrischen Sicherheit wird dieses Geflecht mit einer PVC-Ummantelung isoliert. Die Enden werden in der Regel durch ein Pressschweißverfahren abgeschlossen. Bei dieser Bauweise sind Querschnitte bis maximal 240 mm² üblich. Für höhere Querschnitte werden mehrlagige Kupfergeflechte eingesetzt, deren Enden mit Kabelschuhen verpresst werden. 

Der wesentliche Unterschied zwischen starren und flexiblen Kupferschienen liegt in ihrem Aufbau sowie den daraus resultierenden Einsatzmöglichkeiten. Starre Kupferschienen sind bei großen Querschnitten nur schwer zu biegen und weisen dadurch eingeschränkte Einsatzmöglichkeiten auf. Verbindungen müssen in diesen Fällen häufig über Kabel oder zusätzliche Verbindungselemente realisiert werden. Allerdings können auch Kabel bei großen Querschnitten sehr steif werden, sodass die Handhabung und Installation zunehmend erschwert wird.

Hierin liegt der entscheidende Vorteil flexibler Kupferschienen: Durch ihren Lamellenaufbau lassen sich deutlich engere Biegeradien sowie komplexe Geometrien umsetzen, was den Einsatzbereich wesentlich erweitert. Der Nachteil dieser Bauform besteht jedoch in den höheren Anschaffungskosten. Eine weitere Variante stellen Kupfergeflechte dar, die im Vergleich zu Kabeln gleichen Querschnitts nochmals flexibler sind und damit in Anwendungen mit besonderen Anforderungen an die Beweglichkeit oder Schwingungsdämpfung bevorzugt eingesetzt werden.

Auf die detaillierten technischen Unterschiede und deren Auswirkungen auf Stromtragfähigkeit, Erwärmungsverhalten und mechanische Eigenschaften wird in @TechnischeAnalyse näher eingegangen.

== Normative Anforderungen <NormativeAnforderungen>

Im Schaltschrankbau spielen normative Anforderungen eine zentrale Rolle, um die Sicherheit, Funktionalität und internationale Marktfähigkeit elektrischer Anlagen zu gewährleisten. Die wichtigsten Normensysteme in diesem Bereich sind die IEC-Normen (International Electrotechnical Commission) und die UL-Normen (Underwriters Laboratories), die jeweils unterschiedliche geografische und regulatorische Anforderungen abdecken.

Die internationale Norm IEC 61800-5-1:2022 legt die sicherheitsrelevanten Anforderungen für elektrische Antriebssysteme mit variabler Drehzahl (Power Drive Systems, PDS) fest. Sie beschreibt die grundlegenden Schutzmaßnahmen, die erforderlich sind, um Personen und Anlagen im Betrieb wie auch im Fehlerfall zuverlässig vor Gefahren zu schützen. Der Anwendungsbereich umfasst sowohl Niederspannungs- als auch Hochspannungsantriebssysteme, die aus Leistungsteil, Steuerung und Motor bestehen.

Im Mittelpunkt der Norm stehen drei wesentliche Sicherheitsaspekte: elektrische, thermische und energiebezogene Gefährdungen. Auf elektrischer Ebene definiert die Norm Maßnahmen gegen den elektrischen Schlag, Anforderungen an Isolierung, Luft- und Kriechstrecken sowie Vorgaben für Schutzmechanismen bei Fehler- und Abnormalbedingungen. Im thermischen Bereich adressiert sie Risiken durch Überhitzung, Brandgefahr und die Begrenzung von zulässigen Temperaturanstiegen an Bauteilen, Leitern und berührbaren Oberflächen. Unter dem Aspekt der Energie betrachtet die Norm insbesondere Kurzschluss- und Überlastschutz, den Umgang mit gespeicherten Energien wie Kondensatoren sowie Schutzmaßnahmen gegen gefährliche Energiefreisetzungen. Darüber hinaus enthält die IEC 61800-5-1 Anforderungen an Gehäuse, Kühlung, Erdung, Verdrahtung, elektromagnetische Verträglichkeit sowie an die Kennzeichnung und Dokumentation. Damit stellt die Norm sicher, dass Antriebssysteme im Schaltschrankbau so ausgeführt werden, dass sie bei ordnungsgemäßer Installation und Wartung keine Gefahr für Personen oder Sachwerte darstellen.

Ergänzend dazu ist die IEC 61439-Reihe von zentraler Bedeutung, da sie die Anforderungen an Niederspannungs-Schaltgerätekombinationen festlegt. Diese Normserie befasst sich insbesondere mit der Dimensionierung von Schaltschränken, einschließlich der Strombelastbarkeit von Sammelschienen, der Kurzschlussfestigkeit, der Erwärmung und der erforderlichen Prüfungen zur Sicherstellung der Betriebssicherheit. Während die IEC 61800-5-1 den Fokus auf die Sicherheit der Antriebssysteme legt, stellt die IEC 61439 sicher, dass der gesamte Schaltschrank mechanisch und elektrisch korrekt ausgelegt ist und die eingesetzten Betriebsmittel unter realen Betriebsbedingungen zuverlässig zusammenwirken.

Für den nordamerikanischen Markt ist zusätzlich die UL 508A Standard for Industrial Control Panels maßgeblich. Diese Norm definiert die sicherheitstechnischen Anforderungen an den Aufbau von industriellen Schaltschränken und Steuerungen. Sie regelt unter anderem die Auslegung von Stromschienen, Leiterquerschnitten und Schutzorganen sowie die Dimensionierung von Luft- und Kriechstrecken. Ein besonderer Schwerpunkt liegt dabei auf dem Schutz vor elektrischen Gefährdungen, der korrekten Absicherung gegen Kurzschluss und Überlast sowie auf den Anforderungen an die Erdung und den Berührungsschutz. Darüber hinaus enthält die UL 508A praxisnahe Vorgaben für den Aufbau, die Verdrahtung, die Dokumentation und die Kennzeichnung von Schaltschränken. Sie bildet damit die Grundlage für eine normgerechte und sichere Ausführung von Steuerungs- und Antriebssystemen für den nordamerikanischen Markt.



