#import "../lib/lib.typ": *
#pagebreak()
= Stand der Technik <StandDerTechnik> 
In diesem Kapitel wird der aktuelle Stand der Technik und Forschung im Bereich Kupferschienen im Schaltschrankbau dargestellt. Zunächst werden die derzeit im Schaltschrankbau eingesetzten Verbindungstechniken beschrieben. Anschließend werden die Einsatzbereiche und Vorteile flexibler Kupferschienen erläutert. Daraufhin folgt eine Übersicht über bisherige Forschungsarbeiten und industrielle Anwendungen, mit Fokus auf thermische und mechanische Auslegung, Induktivität und #acr("EMV")-Aspekte sowie Kontaktierung und Übergangswiderstände. Abschließend werden aktuelle Trends und zukünftige Forschungsperspektiven aufgezeigt.
== Aktuelle Verbindungstechniken im Schaltschrankbau <VerbindungstechnikenSchaltschrankbau>
In den derzeit bei ABB im DC-Schaltschrankbau eingesetzten Systemen werden ausschließlich Kabel und starre Kupferschienen verwendet. Letztere werden zur Montage und zur Erreichung der geforderten Anschlussgeometrien häufig in mehrere Segmente unterteilt. Hauptgründe für den verbreiteten Einsatz sind die hohe Verfügbarkeit, die einfache mechanische Bearbeitung sowie die im Vergleich zu Alternativen geringen Material- und Fertigungskosten.

Die mechanische Befestigung erfolgt über Schraubverbindungen. Ab einer gewissen Länge bzw. bei erhöhten Kurzschlusskräften werden zusätzliche Stützungen mittels isolierender Kunststoffhalter (Hartkunststoff-Isolatoren) an den Schaltschrankverstrebungen vorgesehen, um Durchbiegung und ein mögliches Annähern oder Berühren benachbarter Schienen im Kurzschlussfall zu verhindern@IEC608651[Abschnitt 6.5]. Zur Einhaltung der Luft- und Kriechstrecken wird ein Mindestabstand von typischerweise ≥ 25 mm zwischen aktiven Teilen eingehalten@IEC614391[Abschnitt 8.3.2; 8.3.3; Anhang F]. Die Einhaltung normativer Vorgaben sowie der internen ABB-Standards bedingt eine definierte relative Anordnung der Schienen, welche dadurch oft sehr viel Platz zum Einbau benötigen. Es kann auch in besonderen Fällen dazu kommen das aufgrund von Platzmangel Kupferkabel eingesetzt werden. Diese sehen aber nicht schön aus und sind aufwändiger zu montieren und von den Mitarbeitern vor Ort herzustellen.

#figure(
  image("/chapters/Bachelor/F2S2B.jpg", width: 60%, fit: "stretch"),
  caption: [Stand der Technik @weylandEigeneDarstellunga],
)<StandderTechnik>

Die wirtschaftliche Attraktivität starrer Kupferschienen führt trotz des Montageaufwands (mehrteilige Segmente, zahlreiche Schraubpunkte bei großen Querschnitten) weiterhin zu deren dominierendem Einsatz.

== Einsatzbereiche flexibler Kupferschienen <EinsatzbereicheFlexibleKupferschienen>
Flexible Kupferschienen finden in einer Vielzahl von Anwendungen Einsatz wie Schaltanlagen und Steuergeräte, Transportfahrzeugen, Herstellung elektrischer Geräte, Energieerzeugung und Maschinenbau. Durch die vollflächige Isolierung und daraus resultierende Kurzschlussfestigkeit können Luft- und Kriechstrecken zwischen parallel geführten aktiven Schienen deutlich reduziert werden. Dadurch lassen sich kompaktere, induktionsarme Schienenpakete mit geringerer Schleifenfläche realisieren, was sowohl den Platzbedarf im Schaltschrank als auch parasitäre Induktivitäten senkt @NVentERIFLEXFlexible. In vielen Fällen kann eine Geometrie z.B. mehrfache Ebenenversätze oder 90°-Umlenkungen aus einem einzigen flexiblen Schienenstück gefertigt werden @nVentERIFLEXFlexibar[Abb.], wo bei starren Sammelschienen mehrere Segmente mit zusätzlichen Verschraubungen nötig wären. Dies reduziert Montagezeit, Fehlerquellen wie Übergangswiderstände und  Lockerungen sowie Lagerhaltungsaufwand.

#figure(
  image("/chapters/Bachelor/nVentBeispiel.png", width: 70%, fit: "stretch"),
  caption: [nVent ERIFLEX Flexibar @NVentERIFLEXFlexible],
)<nVentERIFLEXFlexibar>

Gegenüber Kabeln ermöglichen flexible Kupferschienen eine definierte, reproduzierbare Leiterführung mit sauberem Erscheinungsbild und vereinfachter Einhaltung von Abständen. Sie können Kabel in hohen Strombereichen ersetzen, bieten eine höhere Stromtragfähigkeit pro Bauraum und erleichtern thermische Ableitung durch flächige Oberfläche. Die Flexibilität kompensiert Fertigungs- und Montagetoleranzen (Versatz, Winkelfehler) von Bauteilen ohne mechanische Zusatzspannungen auf Klemmen oder Baugruppen zu generieren. Sie reduzieren ebenfalls Vibrationsübertragung auf Anschlussklemmen, vereinfachte Nachrüstungen (z.B. zusätzliche Module) sowie eine bessere Skalierbarkeit für modulare Plattformkonzepte. Insgesamt tragen diese Eigenschaften zu einer beschleunigten Fertigung, verbesserten Betriebssicherheit und höheren Packungsdichte im Schaltschrank bei @NVentERIFLEXFlexible.
#pagebreak() 
== Bisherige Forschung und industrielle Anwendungen <ForschungIndustrielleAnwendungen>
=== Thermische und mechanische Auslegung <ThermischeUndMechanischeAuslegung>
Nach IEC 61439-1 dürfen Temperatursteigerungen bis etwa 1.600A berechnet werden, dabei sind Formfaktoren wie z.B. Derating bei Einbaubedingungen zu berücksichtigen. Bei Strömen darüber ist ein Prüfverfahren gefordert.@deffaaDesignHandbuchDCcabinets2024@IEC614391 In der Forschung gewinnen gekoppelte Simulationen zunehmend an Bedeutung, bei denen elektromagnetische, thermische und Strömungseffekte #acrs("CFD") gemeinsam betrachtet werden, um realitätsnahe Temperaturverteilungen und mechanische Beanspruchungen zu modellieren. Kontaktwiderstände, insbesondere an Verschraubungen, sind als potenzielle Hotspots besonders kritisch.@CoupledElectricMagnetic@ThermischesDesignDurch

=== Induktivität und #acr("EMV")-Aspekte <InduktivitaetUndEMVAspekte>
Durch den zunehmenden Einsatz schneller Leistungselektronik wie z.B. Umrichter mit #acr("SiC")-/#acr("GaN")-Halbleiterelektronik rückt die parasitäre Induktivität der Sammelschienen in den Fokus. Flexible Kupferschienen reduzieren die Induktivität signifikant, da die Ströme in eng gepaarten Lagen geführt werden. Dies minimiert Überspannungsspitzen und verbessert das #acrs("EMV")-Probleme. Simulationen zeigen, dass optimierte Geometrien wie z.B. Mehrschichtaufbau, minimale Stromkreis-Loop-Fläche die Schleifeninduktanz senken können. Forschungsarbeiten zeigen weiter, dass Schichtanzahl, Abstände, Skin- und Proximitätseffekte maßgeblich das Verhalten beeinflussen und asymmetrische Induktivitäten vermieden werden sollten.@LaminierteStromschienenFuer@NVentERIFLEXFlexible
=== Kontaktierung und Übergangswiderstände <WerkstoffeKontaktierungUndUebergangswiderstaende>
Um die Oxidationsanfälligkeit zu reduzieren und den Übergangswiderstand zu verringern, werden Sammelschienen in der Regel mit Zinn (Sn), Silber (Ag) oder Nickel (Ni) beschichtet. Die Kontaktierung von Sammelschienen erfolgt überwiegend über Schraubverbindungen, bei denen das Anzugsmoment und die resultierende Flächenpressung maßgeblich für den elektrischen Übergangswiderstand sind. Zu geringe Kontaktkräfte führen zu erhöhtem Widerstand und damit zu thermischen Hot-Spots, während zu hohe Kräfte plastische Deformationen und Beschädigungen hervorrufen können. Ergänzend kommen Pressverbindungen (Crimpen) zum Einsatz, insbesondere bei Kabel-auf-Schiene-Anschlüssen. Deren Qualität und Sicherheit werden nach IEC 61238-1-1 durch standardisierte Prüfungen verifiziert.@IEC612381[Anhang F.3; F8]
Der Übergangswiderstand (Rc) beschreibt den zusätzlichen elektrischen Widerstand an Kontaktstellen und ist ein entscheidender Parameter für die Betriebssicherheit. Er hängt im Wesentlichen von der Kontaktkraft, der Oberflächenbeschaffenheit sowie den Betriebsbedingungen ab. Generell gilt, eine höhere Kontaktkraft reduziert Rc, während Oxidationsschichten, Verschmutzungen, Korrosion und Rauigkeit den Widerstand erhöhen. Oberflächenbeschichtungen wie Zinn oder Silber minimieren den Kontaktwiderstand, unterliegen jedoch Alterungsprozessen. Besonders kritisch ist das Auftreten von Hot-Spots, bei denen lokale Erwärmungen den Widerstand exponentiell steigen lassen und dadurch den Alterungsprozess weiter beschleunigen.@timsitElectricalContactResistance1999@UebergangswiderstandErklaerungGlossar
=== Trends und Forschungsperspektiven <TrendsUndForschungspersektiven>
Die aktuelle Forschung zeigt drei große Schwerpunkte, die Digitale Auslegung von elektrischen Verbindungen mithilfe von Machine Learning anhand Simulationen und digitalen Zwilligen, die immer stärker werdende Leistungselektronik mit laminierten Kupferschienen und die Lebensdauerprognose für Modelle die die Alterung von Kontakstellen und Isolationsmaterialien simulieren und bewerten soll.@ThermischesDesignDurch

=== Industrielle Anwendungen <IndustrielleAnwendungen>
Starre und flexible Kupferschienen sind in einer Vielzahl industrieller Anwendungen etabliert. In leistungselektronischen Systemen (Frequenzumrichter, Gleichrichter, DC-Zwischenkreise, Batteriespeicher) gewährleisten sie niederinduktive Strompfade und hohe Stromtragfähigkeit bei kompakter Bauform. In der Gebäude- und Prozessautomation (Heizungs-, Klima- und Lüftungsanlagen) dienen sie der modularen Energieverteilung sowie der Versorgung von Antrieben und Steuergeräten @HlkAnlagen@Prozessautomation. Im Maschinen- und Anlagenbau ermöglichen sie eine reproduzierbare, vibrationsarme Anbindung von Motorabgängen, Leistungsschaltern und Schutzgeräten. In Ladeinfrastruktur- und E-Mobilitätsanwendungen unterstützen insbesondere flexibel isolierte Ausführungen die Realisierung hochverdichteter, thermisch optimierter Baugruppen @HlkAnlagen@Prozessautomation. Weitere Einsatzfelder umfassen Photovoltaik-Kopplungen, Energiespeichersysteme und USV-Anlagen, in denen geringe Übergangswiderstände, EMV-optimierte Leiterführung und Wartungsfreundlichkeit gefordert sind @HlkAnlagen@GeschaftsbereichPowerGrids@Prozessautomation.