#import "../lib/lib.typ": *

= Methodik <Methodik>
Dieses Kapitel beschreibt die methodische Vorgehensweise zur Entscheidungsfindung im Rahmen der vorliegenden Arbeit. Im Zentrum steht eine Business Case Analyse, welche die wirtschaftliche Bewertung der Umstellung von starren auf flexible Kupferschienen im Schaltschrankbau bei der ABB AG ermöglicht. Ergänzend wird eine Risikoanalyse durchgeführt, um potenzielle Unsicherheiten und Einflussfaktoren zu bewerten. Abschließend erfolgt eine technische Analyse zur Beurteilung der praktischen Umsetzbarkeit der bevorzugten Option.
== Vorgehensweise zur Analyse<VorgehensweiseAnalyse>
Im Zentrum der methodischen Herangehensweise steht die Durchführung einer Business Case Analyse, welche die Grundlage für die wirtschaftliche und qualitative Bewertung der betrachteten Handlungsalternativen bildet. Hierzu werden zwei Hauptoptionen definiert: (1) die Fortführung der bisherigen Praxis mit starren Kupferschienen und (2) die Umstellung auf flexible, vorkonfektionierte Kupferschienen. Ziel ist es, beide Alternativen hinsichtlich ihrer Wirtschaftlichkeit, betrieblichen Effizienz sowie weiterer qualitativer Kriterien systematisch zu vergleichen [1]. Dabei wird nicht nur ein vollständiger Ersatz durch flexible Kupferschienen untersucht, sondern auch die Möglichkeit eines teilweisen Einsatzes in Betracht gezogen. Es ist denkbar, dass sich der Einsatz flexibler Kupferschienen nur in bestimmten Bereichen des Schaltschranks wie etwa bei besonders komplexen oder platzkritischen Verbindungssituationen als wirtschaftlich und technisch vorteilhaft erweist. Diese gemischte Variante wird im weiteren Verlauf der Analyse ergänzend berücksichtigt.

Die Analyse erfolgt in mehreren Stufen: Zunächst werden die relevanten Parameter ermittelt und in einem strukturierten Kriterienkatalog zusammengeführt. Darauf aufbauend werden quantitative Daten, wie z.B. Investitions- und Betriebskosten, erfasst und mithilfe ausgewählter finanzmathematischer Methoden bewertet. Zum Einsatz kommen hierbei insbesondere die Kapitalwertmethode (Net Present Value, NPV), die Rentabilitätsrechnung, die statische Amortisationsdauer sowie der Interne Zinsfuß (Internal Rate of Return, IRR). Diese Methoden ermöglichen eine differenzierte Betrachtung der Wirtschaftlichkeit, indem sie sowohl den zeitlichen Rückfluss der Investition, den Wertzuwachs als auch die durchschnittliche Verzinsung berücksichtigen. Auf eine Gewinnvergleichsrechnung sowie die Endwertmethode wird bewusst verzichtet, da deren Informationsgehalt im Vergleich zur Kapitalwertmethode begrenzt ist bzw. Redundanzen entstehen würden. Ergänzend wird bei Bedarf eine Break-Even-Analyse durchgeführt, um Schwellenwerte wie Mindeststückzahlen für die Wirtschaftlichkeit zu identifizieren. Ergänzend wird eine qualitative Bewertung mittels Nutzwertanalyse durchgeführt, um auch nicht-monetäre Faktoren angemessen zu berücksichtigen. Die Ergebnisse dieser Analysen bilden die Grundlage für eine begründete Handlungsempfehlung [2].
== Verwendete Softwaretools <VerwendeteSoftwaretools>
Zur Durchführung der quantitativen und qualitativen Analysen werden verschiedene Softwaretools eingesetzt, die eine präzise Berechnung, Visualisierung und Dokumentation der Ergebnisse ermöglichen.

Die Wirtschaftlichkeitsanalysen werden primär mithilfe von Microsoft Excel durchgeführt. Hierbei werden standardisierte Rechenmodelle zur Kapitalwertberechnung, Rentabilitätsrechnung, Amortisationsberechnung sowie zur Berechnung des Internen Zinsfußes (IRR) und zur Break-Even-Analyse eingesetzt, welche auf den erhobenen Daten basieren [1]. Für Sensitivitätsanalysen und zur Abbildung unterschiedlicher Szenarien (z.B. Änderungen bei Montagezeit oder Materialkosten) wird ebenfalls Excel verwendet.

Für die Risikoanalyse sowie mögliche Monte-Carlo-Simulationen kommt die Programmiersprache Python zum Einsatz, insbesondere unter Verwendung von Bibliotheken wie NumPy, pandas und Matplotlib. Dies ermöglicht eine detaillierte Analyse der Auswirkungen von Unsicherheiten auf die Entscheidungsfindung.

Zur Erstellung von Entscheidungsbäumen, Prozessdiagrammen und zur visuellen Aufbereitung der Analyseergebnisse werden zusätzlich Visualisierungstools wie Lucidchart oder Microsoft Visio genutzt. Die gesamte Dokumentation erfolgt in Typst, einem LaTeX-ähnlichen Schreibprogramm, insbesondere für die formale Darstellung von mathematischen Modellen und Gleichungen.
== Kriterienkatalog für die Bewertung <KriterienkatalogBewertung>
Ein zentraler Bestandteil der Analyse ist die Definition und Anwendung eines umfassenden Kriterienkatalogs zur Bewertung der beiden Handlungsalternativen. Dieser umfasst sowohl quantitative als auch qualitative Kriterien, die eine ganzheitliche Betrachtung ermöglichen [3].

Zu den quantitativen Kriterien zählen unter anderem die Materialkosten, die Montagezeit (in Stunden), der Personalaufwand, potenzielle Fehler- und Nacharbeitskosten sowie Lager- und Werkzeugkosten. Diese Parameter lassen sich unmittelbar in monetäre Größen überführen und bilden somit die Grundlage für die ökonomische Bewertung im Rahmen der Kapitalwert-, Rentabilitäts-, Amortisations- und IRR-Analyse sowie optional eine Break-Even-Analyse.

Die qualitativen Kriterien umfassen Aspekte wie die Layout-Flexibilität innerhalb des Schaltschrankdesigns, die Sicherheitsaspekte (z.B. bei Vibration oder thermischer Ausdehnung), der Schulungsaufwand für das Bedien- und Montagepersonal sowie der Innovationsgrad der Lösung und ihr potenzieller Einfluss auf das Unternehmensimage.

Die Bewertung der qualitativen Kriterien erfolgt mittels einer Nutzwertanalyse. Hierbei werden die Kriterien zunächst gewichtet, beispielsweise durch Expertenbefragungen oder interne Workshops und anschließend auf einer Skala von 1 bis 5 bewertet. Die aggregierten Bewertungen werden in einer Matrix zusammengeführt, sodass eine vergleichende Gesamtbewertung der beiden Alternativen möglich ist.

=== Risikoanalyse
Zur Ergänzung der wirtschaftlichen und qualitativen Bewertung wird eine Risikoanalyse durchgeführt, mit dem Ziel, die Auswirkungen von Unsicherheiten und Schwankungen auf die Entscheidungssicherheit zu untersuchen. Dabei werden zentrale Parameter, die einen signifikanten Einfluss auf das Ergebnis der Business Case Analyse haben können, systematisch variiert und hinsichtlich ihrer Sensitivität analysiert [1].

Die Risikoanalyse erfolgt in zwei Stufen: Zunächst wird eine Sensitivitätsanalyse durchgeführt, in der gezielt einzelne Variablen wie Montagezeit, Materialpreise oder Personalstundensätze verändert werden, um deren Einfluss auf den Kapitalwert bzw. die Gesamtbewertung zu ermitteln. Anschließend werden unterschiedliche Szenarien (Best-Case, Realistic-Case und Worst-Case) definiert, um die Robustheit der Ergebnisse gegenüber realistischen Schwankungen im Projektumfeld zu prüfen.

Optional kann eine Monte-Carlo-Simulation durchgeführt werden, bei der auf Basis definierter Wahrscheinlichkeitsverteilungen zahlreiche zufällige Kombinationen von Eingabewerten simuliert werden. Dies ermöglicht eine probabilistische Einschätzung der Erfolgschancen der betrachteten Alternativen und bietet eine fundierte Basis für risikobewusste Entscheidungen.

-----------------------------------------------------------

Projekte zeichnen sich durch eine Vielzahl an Unsicherheiten aus, die sowohl auf interne als auch auf externe Einflussfaktoren zurückzuführen sind. Solche Einflussgrößen können den Projektverlauf erheblich beeinträchtigen und im ungünstigsten Fall das Erreichen der Projektziele gefährden. Eine systematische Risikobetrachtung trägt daher wesentlich dazu bei, potenzielle Störungen frühzeitig zu erkennen und die Erfolgschancen eines Projekts signifikant zu erhöhen [18, S. 232 ff.].
Um die Bedeutung des Risikomanagements im Projektkontext angemessen einordnen zu können, ist zunächst eine begriffliche Klärung des Projektbegriffs erforderlich. Ein Projekt wird in der einschlägigen Fachliteratur als ein zielgerichtetes, einmaliges Vorhaben verstanden, das aus einer Menge abgestimmter und gesteuerter Tätigkeiten besteht und durchgeführt wird, um unter Berücksichtigung vorgegebener Rahmenbedingungen wie Zeit, Ressourcen und Qualität ein definiertes Ziel zu erreichen [19, S. 155 ff.]. In Übereinstimmung mit der Norm DIN 69901-5 ist ein Projekt zusätzlich durch die Einmaligkeit seiner Gesamtkonstellation gekennzeichnet [20, Kap. 3.44].
Die Praxis zeigt, dass Projekte insbesondere dann gefährdet sind, wenn zu Beginn unklare Zieldefinitionen oder Kommunikationsdefizite bestehen. Unvollständig abgestimmte Anforderungen gelten dabei als einer der häufigsten Risikofaktoren bei der Projektinitialisierung [21].
Vor diesem Hintergrund wird im Folgenden eine projektspezifische Risikoanalyse durchgeführt, die der systematischen Identifikation und Bewertung relevanter Risiken im Rahmen dieser Bachelorarbeit dient. Das Ziel ist es, potenzielle Störquellen frühzeitig zu erkennen und geeignete Maßnahmen zur Risikominderung abzuleiten. Die Vorgehensweise folgt einem dreistufigen Modell, das die Identifikation relevanter Projektrisiken, die Bewertung der Risiken anhand einer Risikomatrix und die Ableitung sowie Planung geeigneter Gegenmaßnahmen in Abhängigkeit vom ermittelten Risikopotenzial umfasst [22, Kap. 8.2].
Die vollständige Übersicht der identifizierten Projektrisiken einschließlich ihrer Kategorisierung und Bewertung ist in Anhang B dokumentiert. 

=== Risikoidentifikation

Im ersten Schritt der Analyse erfolgt die Identifikation jener Risiken, die im Kontext dieser Bachelorarbeit als besonders relevant eingeschätzt werden. Die Auswahl basiert auf Erfahrungswerten aus vergleichbaren Projekten sowie auf spezifischen Rahmenbedingungen des vorliegenden Vorhabens. Insgesamt werden neun zentrale Projektrisiken betrachtet, die vier übergeordneten Risikodimensionen zugeordnet sind: Organisation, Technologie, Forschung und unternehmerischer Kontext.
Im Folgenden werden diese Risikofelder exemplarisch erläutert und mit konkreten Risiken aus dem Projektverlauf verknüpft.
Organisation: Organisatorische Risiken spielen im Rahmen dieser Bachelorarbeit eine zentrale Rolle, da sie unmittelbaren Einfluss auf die Bearbeitbarkeit, die Koordination sowie die Verfügbarkeit relevanter Ressourcen haben. Ein besonders gravierendes Risiko stellt die eingeschränkte Verfügbarkeit zentraler Ansprechpartner:innen dar, etwa infolge von Urlaubszeiten oder krankheitsbedingten Ausfällen. Da in verschiedenen Projektphasen auf spezifisches Fachwissen zurückgegriffen werden muss, können selbst kurzfristige Abwesenheiten zu erheblichen Verzögerungen im Arbeitsverlauf führen (siehe Anhang B, ID 1 – Mensch).
Zudem besteht eine ausgeprägte Abhängigkeit von global verteilten Einheiten. Projektrelevante Informationen und Freigaben müssen über zentrale Stellen im internationalen Unternehmenskontext eingeholt werden. Diese Abhängigkeit ist mit erhöhtem Koordinationsaufwand verbunden und birgt das Risiko, dass der Projektfortschritt durch ausbleibende oder verspätete Rückmeldungen beeinträchtigt wird (siehe Anhang B, ID 5 – Abhängigkeit).
Ein weiteres Risiko ergibt sich aus zeitlichen Zielkonflikten. Parallel laufende Aufgaben oder private Verpflichtungen verringern die tatsächlich verfügbare Bearbeitungskapazität innerhalb des begrenzten Zeitrahmens dieser Bachelorarbeit. Besonders bei aufeinander aufbauenden Arbeitspaketen kann eine unzureichende zeitliche Abstimmung zu Terminverzögerungen oder Qualitätseinbußen führen (siehe Anhang B, ID 4 – Zeitmanagement/ Deadlines).
Darüber hinaus können auch kommunikative Herausforderungen zu Verzögerungen führen. Sprachliche Unterschiede, uneinheitliche Terminologien und heterogene Abstimmungsprozesse im internationalen Konzernumfeld erschweren insbesondere die konzernweite Koordination und bergen ein erhebliches Risiko für Missverständnisse im Projektverlauf (siehe Anhang B, ID 7 – Kommunikation).
Technologie: Technologische Risiken ergeben sich vor allem aus infrastrukturellen Einschränkungen sowie begrenztem projektspezifischem Know-how im Umgang mit modernen Middleware-Architekturen. Ein zentrales Risiko stellt in diesem Zusammenhang das noch unvollständig aufgebaute Fachwissen im Bereich ROS 2 dar. Insbesondere in frühen Projektphasen kann ein Mangel an Erfahrung zu fehleranfälligen Implementierungen oder erhöhtem Einarbeitungsaufwand führen (siehe Anhang B, ID 2 – Fachwissen).
Ein weiteres Risiko betrifft den eingeschränkten administrativen Zugriff auf die Systemumgebung. Bestimmte Installationen und Netzwerkkonfigurationen erfordern Administratorrechte, die nicht ohne Weiteres zur Verfügung stehen. In der Folge besteht die Gefahr, dass zentrale technische Aufgaben nicht im vorgesehenen Umfang umgesetzt werden können (siehe Anhang B, ID 8 – Eingeschränkter Datenzugriff).
Ergänzend wurde im Rahmen der Projektplanung das Risiko eines Hardwarewechsels während der Bearbeitungszeit identifiziert. Besonders bei komplexen Entwicklungsumgebungen führt ein solcher Systemwechsel zu erheblichem Mehraufwand, da die Arbeitsumgebung vollständig neu eingerichtet und sämtliche Konfigurationen erneut vorgenommen werden müssen (siehe Anhang B, ID 9 – Mensch).
Forschung: Ein wesentliches Risiko im Bereich Forschung betrifft die Rücklaufquote der geplanten Stakeholderbefragung. Bei zu geringer Beteiligung besteht die Gefahr, dass die erhobenen Daten nicht ausreichen, um belastbare oder generalisierbare Aussagen zu ermöglichen. In der Folge könnte die Analyse ein verzerrtes oder unvollständiges Bild der tatsächlichen Bedarfe vermitteln (siehe Anhang B, ID 6 – Stakeholder-Feedback).
Unternehmerischer Kontext: Ein weiteres Risiko ergibt sich aus dem neuartigen Charakter der ROS 2-Integration im Kontext von ABB. Da bislang keine unternehmensinternen Referenzprojekte oder etablierten Best Practices vorliegen, fehlen belastbare Erfahrungswerte für Architekturentscheidungen, Schnittstellenstandards und Entwicklungsprozesse. Dies erschwert den Entwicklungsprozess erheblich, da bei konkreten Umsetzungsfragen nur in begrenztem Umfang auf interne Unterstützung oder etablierte Lösungsansätze zurückgegriffen werden kann (siehe Anhang B, ID 3 – Produkt).

=== Risikobewertung

Nach der Identifikation der Risiken erfolgt deren Bewertung anhand zweier zentraler Bewertungsgrößen: der Eintrittswahrscheinlichkeit (eng. Probability) und des potenziellen Schadensausmaßes (eng. Impact). Die Eintrittswahrscheinlichkeit wird prozentual erfasst, während das Schadensausmaß anhand einer Skala von 1 (gering) bis 5 (sehr hoch) eingeschätzt wird. Aus dem Produkt dieser beiden Faktoren ergibt sich der sogenannte Risk Exposure Index (z. Dt. Risikoexpositionsindex, REI), der als Maß für die Dringlichkeit weiterer Maßnahmen herangezogen wird [23, Kap. 17.1], [24].
Risiken mit einer hohen Eintrittswahrscheinlichkeit und einem zugleich gravierenden Schadenspotenzial führen zu einem entsprechend hohen REI-Wert und gelten im Rahmen dieser Arbeit als besonders kritisch. In solchen Fällen ist eine frühzeitige und gezielte Risikosteuerung erforderlich. Risiken mit niedrigerem REI sind zwar nicht zu vernachlässigen, erfordern jedoch in der Regel lediglich eine beobachtende oder reaktive Behandlung.
Zur Einordnung der ermittelten Werte wird ein dreistufiges Bewertungsschema herangezogen. Dieses unterscheidet zwischen den folgenden Risikostufen:
kritisch (REI ≥ 3,0)
mittel (1,5 ≤ REI < 3,0)
gering (REI < 1,5)

=== Risikobehandlung

Wie Abbildung 4.1 verdeutlicht, wird zur besseren Visualisierung der Ergebnisse die Kategorisierung zusätzlich durch ein Farbschema unterstützt, das sich an der etablierten Ampellogik orientiert: Kritische Risiken werden rot, mittlere Risiken gelb und geringe Risiken grün markiert. Diese farbliche Codierung erleichtert die unmittelbare Einordnung des Handlungsbedarfs innerhalb der Risikomatrix.
 
Abb. 4.1 Exemplarischer Auszug aus der Risikomatrix zur Identifikation, Bewertung und Einordnung projektspezifischer Risiken. Die farbliche Codierung orientiert sich am Ampelsystem: kritisch (rot) bei REI ≥ 3,0, mittel (gelb) bei 1,5 ≤ REI < 3,0, und gering (grün) bei REI < 1,5. (Quelle: Eigene Darstellung, vgl. Anhang B)
Auf Grundlage der durchgeführten Bewertung wurden für sämtliche identifizierten Risiken geeignete Maßnahmen entwickelt. Im Fokus der folgenden Ausführungen stehen jedoch jene vier Projektrisiken, deren REI den Schwellenwert von 3,0 überschreitet und die somit als besonders kritisch einzustufen sind. Diese weisen ein erhöhtes Gefährdungspotenzial für den erfolgreichen Verlauf der Bachelorarbeit auf und erfordern eine besonders sorgfältige Risikosteuerung.
Im Folgenden werden die jeweiligen Gegenmaßnahmen für diese vier kritisch bewerteten Projektrisiken dargestellt.
Mensch (ID 1 – REI 3,8): Zur präventiven Risikominimierung wird frühzeitig eine transparente Abwesenheitsplanung vorgenommen. Darüber hinaus werden geeignete Vertretungen benannt, die im Falle einer Abwesenheit als Ansprechpersonen einspringen können. Die zentralen Projektergebnisse werden fortlaufend dokumentiert, sodass auch bei kurzfristigen Ausfällen ein gesicherter Informationsstand gewährleistet ist.
Abhängigkeit (ID 5 – REI: 4,0): Um die Risiken durch externe Abhängigkeiten zu minimieren, werden erforderliche Freigaben und projektrelevante Informationen frühzeitig bei den zuständigen Stellen angefragt. Gleichzeitig wird ein Eskalationspfad definiert, der es ermöglicht, bei ausbleibenden Rückmeldungen zeitnah alternative Ansprechpersonen einzubinden oder Entscheidungen auf höherer Ebene herbeizuführen.
Stakeholderfeedback (ID 6 – REI: 3,6): Zur Erhöhung der Rücklaufquote bei der Stakeholderbefragung werden gezielte Maßnahmen zur Aktivierung der Teilnehmenden umgesetzt. Dazu zählen unter anderem personalisierte Reminder, ein klar kommunizierter Mehrwert der Teilnahme sowie die Nutzung bestehender persönlicher Netzwerke. Sollte trotz dieser Maßnahmen die Beteiligung unter den Erwartungen bleiben, ist ergänzend eine ergänzende Desk-Research-Phase (z. Dt. Schreibtischrecherche bzw. Sekundärforschung) vorgesehen, um zentrale Hypothesen zumindest indirekt abzusichern.
Kommunikation (ID 7 – REI: 3,6): Zur Reduzierung kommunikativer Reibungsverluste in einem internationalen Projektumfeld werden sämtliche Projektdokumente sowohl in deutscher als auch englischer Sprache erstellt. Zudem werden regelmäßige, kurze Abstimmungstermine etabliert, um den Informationsfluss zu gewährleisten. 

[18]         F. Romeike und P. Hager, Erfolgsfaktor Risiko-Management 4.0: Methoden, Beispiele, Checklisten Praxishandbuch für Industrie und Handel. Wiesbaden: Springer Fachmedien Wiesbaden, 2020. doi: 10.1007/978-3-658-29446-5.
[19]     M. Helmold, Kaizen, Lean Management und Digitalisierung: Mit den japanischen Konzepten Wettbewerbsvorteile für das Unternehmen erzielen. Wiesbaden: Springer Fachmedien Wiesbaden, 2021. doi: 10.1007/978-3-658-32342-4.
[20]     DIN e.V. (Hrsg.), „DIN 69901-5:2009-01, Projektmanagement - Projektmanagementsysteme - Teil 5: Begriffe“, Beuth-Verlag, Berlin, Jan. 2009.
[21]     Asana, „7 häufige Projektrisiken und wie man sie vermeidet [2025] • Asana“, Asana. Zugegriffen: 29. Juni 2025. [Online]. Verfügbar unter: https://asana.com/de/resources/project-risks
[22]     W. Jakoby, Projektmanagement für Ingenieure: Ein praxisnahes Lehrbuch für den systematischen Projekterfolg. Wiesbaden: Springer Fachmedien Wiesbaden, 2021. doi: 10.1007/978-3-658-32791-0.
[23]     H. Kerzner, Project management: a systems approach to planning, scheduling, and controlling, Twelfth edition. Hoboken, New Jersey: Wiley, 2017.
[24]     T. Admin, „Project Risk Analysis Formulas Explained“, Teamhub | Projects, Chat and Docs in a single platform. Zugegriffen: 29. Juni 2025. [Online]. Verfügbar unter: https://teamhub.com/blog/project-risk-analysis-formulas-explained/

== Technische Analyse <TechnischeAnalyse>
Neben der wirtschaftlichen Bewertung ist auch die technische Umsetzbarkeit der favorisierten Lösung von zentraler Bedeutung. Daher erfolgt im letzten Schritt eine technische Analyse, welche die Praxistauglichkeit und Integrationsfähigkeit der flexiblen Kupferschienen im bestehenden Schaltschrankbau bei ABB untersucht.

Die Analyse umfasst dabei mehrere Dimensionen: Zum einen wird geprüft, inwieweit die neuen Komponenten mit den bestehenden Fertigungsprozessen, Maschinen und Montagesystemen kompatibel sind. Zum anderen werden mögliche technische Vorteile (z.B. geringerer Platzbedarf, einfachere Handhabung, optimierte Stromverteilung) sowie potenzielle Herausforderungen (z.B. Anschlussnormen, Langzeitverhalten, Zertifizierungsanforderungen) identifiziert.

Darüber hinaus erfolgt eine Bewertung hinsichtlich Wartungsfreundlichkeit, Zuverlässigkeit und Lebensdauer der flexiblen Kupferschienen. Ziel dieser Analyse ist es, sicherzustellen, dass die gewählte technische Lösung nicht nur ökonomisch vorteilhaft, sondern auch langfristig funktional und betrieblich umsetzbar ist.

Diese ganzheitliche methodische Vorgehensweise stellt sicher, dass sowohl wirtschaftliche als auch technische Aspekte umfassend berücksichtigt werden und die finale Entscheidung auf einer fundierten, nachvollziehbaren Basis erfolgt.

Literaturverzeichnis (IEEE-Stil):

[1] A. Taschner, Business Cases, Wiesbaden: Springer Fachmedien, 2017. [Online]. Verfügbar: https://link.springer.com/book/10.1007/978-3-658-16479-6

[2] L. O. Meertens, M.-E. Iacob, and B. J. Nieuwenhuis, "Creating a Business Case from a Business Model," in Business Modeling and Software Design, Springer, Cham, 2013, pp. 45–60. [Online]. Verfügbar: https://link.springer.com/chapter/10.1007/978-3-319-06671-4_3

[3] R. Weiber and M. Sarstedt, Strukturgleichungsmodellierung – Eine anwendungsorientierte Einführung, 3. Aufl., Berlin: Springer Gabler, 2021. [Online]. Verfügbar: https://link.springer.com/book/10.1007/978-3-658-35385-5