#import "../lib/lib.typ": *

= Methodik <Methodik>

== Vorgehensweise zur Analyse<VorgehensweiseAnalyse>
== Verwendete Softwaretools <VerwendeteSoftwaretools>
== Kriterienkatalog für die Bewertung <KriterienkatalogBewertung>

=== Risikoanalyse
Projekte zeichnen sich durch eine Vielzahl an Unsicherheiten aus, die sowohl auf interne als auch auf externe Einflussfaktoren zurückzuführen sind. Solche Einflussgrößen können den Projektverlauf erheblich beeinträchtigen und im ungünstigsten Fall das Erreichen der Projektziele gefährden. Eine systematische Risikobetrachtung trägt daher wesentlich dazu bei, potenzielle Störungen frühzeitig zu erkennen und die Erfolgschancen eines Projekts signifikant zu erhöhen [18, S. 232 ff.].
Um die Bedeutung des Risikomanagements im Projektkontext angemessen einordnen zu können, ist zunächst eine begriffliche Klärung des Projektbegriffs erforderlich. Ein Projekt wird in der einschlägigen Fachliteratur als ein zielgerichtetes, einmaliges Vorhaben verstanden, das aus einer Menge abgestimmter und gesteuerter Tätigkeiten besteht und durchgeführt wird, um unter Berücksichtigung vorgegebener Rahmenbedingungen wie Zeit, Ressourcen und Qualität ein definiertes Ziel zu erreichen [19, S. 155 ff.]. In Übereinstimmung mit der Norm DIN 69901-5 ist ein Projekt zusätzlich durch die Einmaligkeit seiner Gesamtkonstellation gekennzeichnet [20, Kap. 3.44].
Die Praxis zeigt, dass Projekte insbesondere dann gefährdet sind, wenn zu Beginn unklare Zieldefinitionen oder Kommunikationsdefizite bestehen. Unvollständig abgestimmte Anforderungen gelten dabei als einer der häufigsten Risikofaktoren bei der Projektinitialisierung [21].
Vor diesem Hintergrund wird im Folgenden eine projektspezifische Risikoanalyse durchgeführt, die der systematischen Identifikation und Bewertung relevanter Risiken im Rahmen dieser Bachelorarbeit dient. Das Ziel ist es, potenzielle Störquellen frühzeitig zu erkennen und geeignete Maßnahmen zur Risikominderung abzuleiten. Die Vorgehensweise folgt einem dreistufigen Modell, das die Identifikation relevanter Projektrisiken, die Bewertung der Risiken anhand einer Risikomatrix und die Ableitung sowie Planung geeigneter Gegenmaßnahmen in Abhängigkeit vom ermittelten Risikopotenzial umfasst [22, Kap. 8.2].
Die vollständige Übersicht der identifizierten Projektrisiken einschließlich ihrer Kategorisierung und Bewertung ist in Anhang B dokumentiert. 

=== Risikoidentifikation

Im ersten Schritt der Analyse erfolgt die Identifikation jener Risiken, die im Kontext dieser Bachelorarbeit als besonders relevant eingeschätzt werden. Die Auswahl basiert auf Erfahrungswerten aus vergleichbaren Projekten sowie auf spezifischen Rahmenbedingungen des vorliegenden Vorhabens. Insgesamt werden neun zentrale Projektrisiken betrachtet, die vier übergeordneten Risikodimensionen zugeordnet sind: Organisation, Technologie, Forschung und unternehmerischer Kontext.
Im Folgenden werden diese Risikofelder exemplarisch erläutert und mit konkreten Risiken aus dem Projektverlauf verknüpft.
Organisation: Organisatorische Risiken spielen im Rahmen dieser Bachelorarbeit eine zentrale Rolle, da sie unmittelbaren Einfluss auf die Bearbeitbarkeit, die Koordination sowie die Verfügbarkeit relevanter Ressourcen haben. Ein besonders gravierendes Risiko stellt die eingeschränkte Verfügbarkeit zentraler Ansprechpartner:innen dar, etwa infolge von Urlaubszeiten oder krankheitsbedingten Ausfällen. Da in verschiedenen Projektphasen auf spezifisches Fachwissen zurückgegriffen werden muss, können selbst kurzfristige Abwesenheiten zu erheblichen Verzögerungen im Arbeitsverlauf führen (siehe Anhang B, ID 1 – Mensch).
Zudem besteht eine ausgeprägte Abhängigkeit von global verteilten Einheiten. Projektrelevante Informationen und Freigaben müssen über zentrale Stellen im internationalen Unternehmenskontext eingeholt werden. Diese Abhängigkeit ist mit erhöhtem Koordinationsaufwand verbunden und birgt das Risiko, dass der Projektfortschritt durch ausbleibende oder verspätete Rückmeldungen beeinträchtigt wird (siehe Anhang B, ID 5 – Abhängigkeit).
Ein weiteres Risiko ergibt sich aus zeitlichen Zielkonflikten. Parallel laufende Aufgaben oder private Verpflichtungen verringern die tatsächlich verfügbare Bearbeitungskapazität innerhalb des begrenzten Zeitrahmens dieser Bachelorarbeit. Besonders bei aufeinander aufbauenden Arbeitspaketen kann eine unzureichende zeitliche Abstimmung zu Terminverzögerungen oder Qualitätseinbußen führen (siehe Anhang B, ID 4 – Zeitmanagement/ Deadlines).
Darüber hinaus können auch kommunikative Herausforderungen zu Verzögerungen führen. Sprachliche Unterschiede, uneinheitliche Terminologien und heterogene Abstimmungsprozesse im internationalen Konzernumfeld erschweren insbesondere die konzernweite Koordination und bergen ein erhebliches Risiko für Missverständnisse im Projektverlauf (siehe Anhang B, ID 7 – Kommunikation).
Technologie: Technologische Risiken ergeben sich vor allem aus infrastrukturellen Einschränkungen sowie begrenztem projektspezifischem Know-how im Umgang mit modernen Middleware-Architekturen. Ein zentrales Risiko stellt in diesem Zusammenhang das noch unvollständig aufgebaute Fachwissen im Bereich ROS 2 dar. Insbesondere in frühen Projektphasen kann ein Mangel an Erfahrung zu fehleranfälligen Implementierungen oder erhöhtem Einarbeitungsaufwand führen (siehe Anhang B, ID 2 – Fachwissen).
Ein weiteres Risiko betrifft den eingeschränkten administrativen Zugriff auf die Systemumgebung. Bestimmte Installationen und Netzwerkkonfigurationen erfordern Administratorrechte, die nicht ohne Weiteres zur Verfügung stehen. In der Folge besteht die Gefahr, dass zentrale technische Aufgaben nicht im vorgesehenen Umfang umgesetzt werden können (siehe Anhang B, ID 8 – Eingeschränkter Datenzugriff).
Ergänzend wurde im Rahmen der Projektplanung das Risiko eines Hardwarewechsels während der Bearbeitungszeit identifiziert. Besonders bei komplexen Entwicklungsumgebungen führt ein solcher Systemwechsel zu erheblichem Mehraufwand, da die Arbeitsumgebung vollständig neu eingerichtet und sämtliche Konfigurationen erneut vorgenommen werden müssen (siehe Anhang B, ID 9 – Mensch).
Forschung: Ein wesentliches Risiko im Bereich Forschung betrifft die Rücklaufquote der geplanten Stakeholderbefragung. Bei zu geringer Beteiligung besteht die Gefahr, dass die erhobenen Daten nicht ausreichen, um belastbare oder generalisierbare Aussagen zu ermöglichen. In der Folge könnte die Analyse ein verzerrtes oder unvollständiges Bild der tatsächlichen Bedarfe vermitteln (siehe Anhang B, ID 6 – Stakeholder-Feedback).
Unternehmerischer Kontext: Ein weiteres Risiko ergibt sich aus dem neuartigen Charakter der ROS 2-Integration im Kontext von ABB. Da bislang keine unternehmensinternen Referenzprojekte oder etablierten Best Practices vorliegen, fehlen belastbare Erfahrungswerte für Architekturentscheidungen, Schnittstellenstandards und Entwicklungsprozesse. Dies erschwert den Entwicklungsprozess erheblich, da bei konkreten Umsetzungsfragen nur in begrenztem Umfang auf interne Unterstützung oder etablierte Lösungsansätze zurückgegriffen werden kann (siehe Anhang B, ID 3 – Produkt).

=== Risikobewertung

Nach der Identifikation der Risiken erfolgt deren Bewertung anhand zweier zentraler Bewertungsgrößen: der Eintrittswahrscheinlichkeit (eng. Probability) und des potenziellen Schadensausmaßes (eng. Impact). Die Eintrittswahrscheinlichkeit wird prozentual erfasst, während das Schadensausmaß anhand einer Skala von 1 (gering) bis 5 (sehr hoch) eingeschätzt wird. Aus dem Produkt dieser beiden Faktoren ergibt sich der sogenannte Risk Exposure Index (z. Dt. Risikoexpositionsindex, REI), der als Maß für die Dringlichkeit weiterer Maßnahmen herangezogen wird [23, Kap. 17.1], [24].
Risiken mit einer hohen Eintrittswahrscheinlichkeit und einem zugleich gravierenden Schadenspotenzial führen zu einem entsprechend hohen REI-Wert und gelten im Rahmen dieser Arbeit als besonders kritisch. In solchen Fällen ist eine frühzeitige und gezielte Risikosteuerung erforderlich. Risiken mit niedrigerem REI sind zwar nicht zu vernachlässigen, erfordern jedoch in der Regel lediglich eine beobachtende oder reaktive Behandlung.
Zur Einordnung der ermittelten Werte wird ein dreistufiges Bewertungsschema herangezogen. Dieses unterscheidet zwischen den folgenden Risikostufen:
kritisch (REI ≥ 3,0)
mittel (1,5 ≤ REI < 3,0)
gering (REI < 1,5)

=== Risikobehandlung

Wie Abbildung 4.1 verdeutlicht, wird zur besseren Visualisierung der Ergebnisse die Kategorisierung zusätzlich durch ein Farbschema unterstützt, das sich an der etablierten Ampellogik orientiert: Kritische Risiken werden rot, mittlere Risiken gelb und geringe Risiken grün markiert. Diese farbliche Codierung erleichtert die unmittelbare Einordnung des Handlungsbedarfs innerhalb der Risikomatrix.
 
Abb. 4.1 Exemplarischer Auszug aus der Risikomatrix zur Identifikation, Bewertung und Einordnung projektspezifischer Risiken. Die farbliche Codierung orientiert sich am Ampelsystem: kritisch (rot) bei REI ≥ 3,0, mittel (gelb) bei 1,5 ≤ REI < 3,0, und gering (grün) bei REI < 1,5. (Quelle: Eigene Darstellung, vgl. Anhang B)
Auf Grundlage der durchgeführten Bewertung wurden für sämtliche identifizierten Risiken geeignete Maßnahmen entwickelt. Im Fokus der folgenden Ausführungen stehen jedoch jene vier Projektrisiken, deren REI den Schwellenwert von 3,0 überschreitet und die somit als besonders kritisch einzustufen sind. Diese weisen ein erhöhtes Gefährdungspotenzial für den erfolgreichen Verlauf der Bachelorarbeit auf und erfordern eine besonders sorgfältige Risikosteuerung.
Im Folgenden werden die jeweiligen Gegenmaßnahmen für diese vier kritisch bewerteten Projektrisiken dargestellt.
Mensch (ID 1 – REI 3,8): Zur präventiven Risikominimierung wird frühzeitig eine transparente Abwesenheitsplanung vorgenommen. Darüber hinaus werden geeignete Vertretungen benannt, die im Falle einer Abwesenheit als Ansprechpersonen einspringen können. Die zentralen Projektergebnisse werden fortlaufend dokumentiert, sodass auch bei kurzfristigen Ausfällen ein gesicherter Informationsstand gewährleistet ist.
Abhängigkeit (ID 5 – REI: 4,0): Um die Risiken durch externe Abhängigkeiten zu minimieren, werden erforderliche Freigaben und projektrelevante Informationen frühzeitig bei den zuständigen Stellen angefragt. Gleichzeitig wird ein Eskalationspfad definiert, der es ermöglicht, bei ausbleibenden Rückmeldungen zeitnah alternative Ansprechpersonen einzubinden oder Entscheidungen auf höherer Ebene herbeizuführen.
Stakeholderfeedback (ID 6 – REI: 3,6): Zur Erhöhung der Rücklaufquote bei der Stakeholderbefragung werden gezielte Maßnahmen zur Aktivierung der Teilnehmenden umgesetzt. Dazu zählen unter anderem personalisierte Reminder, ein klar kommunizierter Mehrwert der Teilnahme sowie die Nutzung bestehender persönlicher Netzwerke. Sollte trotz dieser Maßnahmen die Beteiligung unter den Erwartungen bleiben, ist ergänzend eine ergänzende Desk-Research-Phase (z. Dt. Schreibtischrecherche bzw. Sekundärforschung) vorgesehen, um zentrale Hypothesen zumindest indirekt abzusichern.
Kommunikation (ID 7 – REI: 3,6): Zur Reduzierung kommunikativer Reibungsverluste in einem internationalen Projektumfeld werden sämtliche Projektdokumente sowohl in deutscher als auch englischer Sprache erstellt. Zudem werden regelmäßige, kurze Abstimmungstermine etabliert, um den Informationsfluss zu gewährleisten. 

[18]         F. Romeike und P. Hager, Erfolgsfaktor Risiko-Management 4.0: Methoden, Beispiele, Checklisten Praxishandbuch für Industrie und Handel. Wiesbaden: Springer Fachmedien Wiesbaden, 2020. doi: 10.1007/978-3-658-29446-5.
[19]     M. Helmold, Kaizen, Lean Management und Digitalisierung: Mit den japanischen Konzepten Wettbewerbsvorteile für das Unternehmen erzielen. Wiesbaden: Springer Fachmedien Wiesbaden, 2021. doi: 10.1007/978-3-658-32342-4.
[20]     DIN e.V. (Hrsg.), „DIN 69901-5:2009-01, Projektmanagement - Projektmanagementsysteme - Teil 5: Begriffe“, Beuth-Verlag, Berlin, Jan. 2009.
[21]     Asana, „7 häufige Projektrisiken und wie man sie vermeidet [2025] • Asana“, Asana. Zugegriffen: 29. Juni 2025. [Online]. Verfügbar unter: https://asana.com/de/resources/project-risks
[22]     W. Jakoby, Projektmanagement für Ingenieure: Ein praxisnahes Lehrbuch für den systematischen Projekterfolg. Wiesbaden: Springer Fachmedien Wiesbaden, 2021. doi: 10.1007/978-3-658-32791-0.
[23]     H. Kerzner, Project management: a systems approach to planning, scheduling, and controlling, Twelfth edition. Hoboken, New Jersey: Wiley, 2017.
[24]     T. Admin, „Project Risk Analysis Formulas Explained“, Teamhub | Projects, Chat and Docs in a single platform. Zugegriffen: 29. Juni 2025. [Online]. Verfügbar unter: https://teamhub.com/blog/project-risk-analysis-formulas-explained/