#import "../lib/lib.typ": *

= Methodik <Methodik>
Dieses Kapitel beschreibt die methodische Vorgehensweise zur Entscheidungsfindung im Rahmen der vorliegenden Arbeit. Im Zentrum steht eine Business Case Analyse, welche die wirtschaftliche Bewertung der Umstellung von starren auf flexible Kupferschienen im Schaltschrankbau bei der ABB AG ermöglicht. Ergänzend wird eine Risikoanalyse durchgeführt, um potenzielle Unsicherheiten und Einflussfaktoren zu bewerten. Abschließend erfolgt eine technische Analyse zur Beurteilung der praktischen Umsetzbarkeit der bevorzugten Option.
== Vorgehensweise zur Analyse<VorgehensweiseAnalyse>
Im Zentrum der methodischen Herangehensweise steht die Durchführung einer Business Case Analyse, welche die Grundlage für die wirtschaftliche und qualitative Bewertung der betrachteten Handlungsalternativen bildet. Hierzu werden drei Hauptoptionen definiert: 1. die Fortführung der bisherigen Praxis mit starren Kupferschienen, 2. die Umstellung auf flexible, vorkonfektionierte Kupferschienen und 3. Eine gemischte Variante aus Starren und flexiblen Kupferschienen. Ziel ist es, alle Alternativen hinsichtlich ihrer Wirtschaftlichkeit, betrieblichen Effizienz sowie weiterer qualitativer Kriterien systematisch zu vergleichen (vgl. @taschnerBusinessCases2017). Dabei wird nicht nur ein vollständiger Ersatz durch flexible Kupferschienen untersucht, sondern auch die Möglichkeit eines teilweisen Einsatzes in Betracht gezogen. Es ist denkbar, dass sich der Einsatz flexibler Kupferschienen nur in bestimmten Bereichen des Schaltschranks wie etwa bei besonders komplexen oder platzkritischen Verbindungssituationen als wirtschaftlich und technisch vorteilhaft erweist. Diese gemischte Variante wird im weiteren Verlauf der Analyse ergänzend berücksichtigt.

Die Analyse erfolgt in mehreren Stufen. Zunächst werden die relevanten Parameter ermittelt und in einem strukturierten Kriterienkatalog zusammengeführt. Darauf aufbauend werden quantitative Daten, wie z.B. Investitions- und Betriebskosten, erfasst und mithilfe ausgewählter finanzmathematischer Methoden bewertet. Zum Einsatz kommen hierbei insbesondere die Kapitalwertmethode (Net Present Value, NPV), die Rentabilitätsrechnung, die statische Amortisationsdauer sowie der Interne Zinsfuß (Internal Rate of Return, IRR). Diese Methoden ermöglichen eine differenzierte Betrachtung der Wirtschaftlichkeit, indem sie sowohl den zeitlichen Rückfluss der Investition, den Wertzuwachs als auch die durchschnittliche Verzinsung berücksichtigen. Auf eine Gewinnvergleichsrechnung sowie die Endwertmethode wird bewusst verzichtet, da deren Informationsgehalt im Vergleich zur Kapitalwertmethode begrenzt ist bzw. Redundanzen entstehen würden. Ergänzend wird bei Bedarf eine Break-Even-Analyse durchgeführt, um Schwellenwerte wie Mindeststückzahlen für die Wirtschaftlichkeit zu identifizieren. Ergänzend wird eine qualitative Bewertung mittels Nutzwertanalyse durchgeführt, um auch nicht-monetäre Faktoren angemessen zu berücksichtigen. Die Ergebnisse dieser Analysen bilden die Grundlage für eine begründete Handlungsempfehlung (vgl. @meertensCreatingBusinessCase2014).
== Verwendete Softwaretools <VerwendeteSoftwaretools>
Zur Durchführung der quantitativen und qualitativen Analysen werden verschiedene Softwaretools eingesetzt, die eine Berechnung, Visualisierung und Dokumentation der Ergebnisse ermöglichen.

Die Wirtschaftlichkeitsanalysen werden primär mithilfe von Microsoft Excel durchgeführt. Hierbei werden standardisierte Rechenmodelle zur Kapitalwertberechnung, Rentabilitätsrechnung, Amortisationsberechnung sowie zur Break-Even-Analyse eingesetzt, welche auf den erhobenen Daten der möglichen Lieferanten und aktuellen Preisen basieren (vgl. @taschnerBusinessCases2017). Für Sensitivitätsanalysen und zur Abbildung unterschiedlicher Szenarien (z.B. Änderungen bei Montagezeit oder Materialkosten) wird ebenfalls Excel verwendet.

Für die Risikoanalyse sowie mögliche Monte-Carlo-Simulationen kommt die Programmiersprache Python zum Einsatz, insbesondere unter Verwendung von Bibliotheken wie NumPy, pandas und Matplotlib. Dies ermöglicht eine detaillierte Analyse der Auswirkungen von Unsicherheiten auf die Entscheidungsfindung.

Zur Erstellung von Entscheidungsbäumen, Prozessdiagrammen und zur visuellen Aufbereitung der Analyseergebnisse werden zusätzlich Visualisierungstools wie Lucidchart genutzt. Die gesamte Dokumentation erfolgt in Typst, einem LaTeX-ähnlichen Schreibprogramm, insbesondere für die formale Darstellung von mathematischen Modellen und Gleichungen.
== Kriterienkatalog für die Bewertung <KriterienkatalogBewertung>
Ein zentraler Bestandteil der Analyse ist die Definition und Anwendung eines umfassenden Kriterienkatalogs zur Bewertung der beiden Handlungsalternativen. Dieser umfasst sowohl quantitative als auch qualitative Kriterien, die eine ganzheitliche Betrachtung ermöglichen (vgl. @weiberStrukturgleichungsmodellierung2009).

Zu den quantitativen Kriterien zählen unter anderem die Materialkosten, die Montagezeit (in Stunden), der Personalaufwand, potenzielle Fehler- und Nacharbeitskosten sowie Lager- und Werkzeugkosten. Diese Parameter lassen sich unmittelbar in monetäre Größen überführen und bilden somit die Grundlage für die ökonomische Bewertung im Rahmen der Kapitalwert-, Rentabilitäts-, Amortisations- und eine Break-Even-Analyse.

Die qualitativen Kriterien umfassen Aspekte wie die Layout-Flexibilität innerhalb des Schaltschrankdesigns, die Sicherheitsaspekte (z.B. im Kurzschlussfall oder thermischer Ausdehnung), der Schulungsaufwand für das Bedien- und Montagepersonal sowie der Innovationsgrad der Lösung und ihr potenzieller Einfluss auf das Unternehmen.

Die Bewertung der qualitativen Kriterien erfolgt mittels einer Nutzwertanalyse. Hierbei werden die Kriterien zunächst gewichtet, beispielsweise durch Expertenbefragungen oder interne Workshops und anschließend auf einer Skala von 1 bis 5 bewertet. Die aggregierten Bewertungen werden in einer Matrix zusammengeführt, sodass eine vergleichende Gesamtbewertung der beiden Alternativen möglich ist.

=== Risikoanalyse
Zur Ergänzung der wirtschaftlichen und qualitativen Bewertung wird eine Risikoanalyse durchgeführt, mit dem Ziel, die Auswirkungen von Unsicherheiten und Schwankungen auf die Entscheidungssicherheit zu untersuchen. Dabei werden zentrale Parameter, die einen signifikanten Einfluss auf das Ergebnis der Business Case Analyse haben können, systematisch variiert und hinsichtlich ihrer Sensitivität analysiert (vgl. @taschnerBusinessCases2017).

Die Risikoanalyse erfolgt in zwei Stufen, Zunächst wird eine Sensitivitätsanalyse durchgeführt, in der gezielt einzelne Variablen wie Montagezeit, Materialpreise oder Personalstundensätze verändert werden, um deren Einfluss auf den Kapitalwert bzw. die Gesamtbewertung zu ermitteln. Anschließend werden unterschiedliche Szenarien (Best-Case, Realistic-Case und Worst-Case) definiert, um die Robustheit der Ergebnisse gegenüber realistischen Schwankungen im Projektumfeld zu prüfen.

Optional kann eine Monte-Carlo-Simulation durchgeführt werden, bei der auf Basis definierter Wahrscheinlichkeitsverteilungen zahlreiche zufällige Kombinationen von Eingabewerten simuliert werden. Dies ermöglicht eine probabilistische Einschätzung der Erfolgschancen der betrachteten Alternativen und bietet eine fundierte Basis für risikobewusste Entscheidungen.

== Technische Bewertung <TechnischeBewertung>
Neben der wirtschaftlichen Bewertung ist auch die technische Umsetzbarkeit der favorisierten Lösung von zentraler Bedeutung. Daher erfolgt im letzten Schritt eine technische Analyse, welche die Praxistauglichkeit und Integrationsfähigkeit der flexiblen Kupferschienen im bestehenden Schaltschrankbau bei ABB untersucht.

Die Analyse umfasst dabei mehrere Dimensionen: Zum einen wird geprüft, inwieweit die neuen Komponenten mit den bestehenden Fertigungsprozessen, Maschinen und Montagesystemen kompatibel sind. Zum anderen werden mögliche technische Vorteile (z.B. geringerer Platzbedarf, einfachere Handhabung, optimierte Stromverteilung) sowie potenzielle Herausforderungen (z.B. Anschlussnormen, Langzeitverhalten, Zertifizierungsanforderungen) identifiziert.

Darüber hinaus erfolgt eine Bewertung hinsichtlich Wartungsfreundlichkeit, Zuverlässigkeit und Lebensdauer der flexiblen Kupferschienen. Ziel dieser Analyse ist es, sicherzustellen, dass die gewählte technische Lösung nicht nur wirtschaftlich vorteilhaft, sondern auch langfristig funktional und betrieblich umsetzbar ist.

Diese ganzheitliche methodische Vorgehensweise stellt sicher, dass sowohl wirtschaftliche als auch technische Aspekte umfassend berücksichtigt werden und die finale Entscheidung auf einer fundierten, nachvollziehbaren Basis erfolgt.
